// THE BLUEPRINT INDEX GENERATOR — every `*.json` in this directory, as one importable module.
//
// ★ WHY A GENERATED FILE: the worker is bundled by esbuild and the host by Next; neither can list a
// directory at runtime, and `placed.ts` needs every blueprint a placement row might name. So the
// list is written down as `index.generated.ts` — by `scripts/gen-blueprints.mts` at prebuild, and by
// the save routes the moment a file is written or removed, so the index never lags the directory
// inside a session. `placed.test.ts` compares the index to the directory and goes red if it does.
//
// Server-side only (fs). The route imports it; the script imports it; nothing in the client does.
import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { SAFE_BLUEPRINT_ID } from '../../voxel/blueprints'

export const BLUEPRINT_DIR = join(process.cwd(), 'src/app/shimmer/data/blueprints')
export const INDEX_FILE = join(BLUEPRINT_DIR, 'index.generated.ts')

export function blueprintFileIds(dir: string = BLUEPRINT_DIR): string[] {
  // ★ A FILE THE ID RULE CANNOT NAME IS NOT A BLUEPRINT. `placed.table.json` lives here and its stem
  // has a dot, which `SAFE_BLUEPRINT_ID` forbids — so it is skipped by rule, not by a hand-kept name.
  return readdirSync(dir).filter(f => f.endsWith('.json')).map(f => f.replace(/\.json$/, '')).filter(id => SAFE_BLUEPRINT_ID.test(id)).sort()
}

export function renderIndex(ids: string[]): string {
  const ident = (id: string) => 'bp_' + id.replace(/[^a-z0-9]/gi, '_')
  return [
    '// GENERATED by data/blueprints/gen-index.ts — do not edit. Regenerated at prebuild and on every save.',
    "import type { BlueprintDef } from '../../voxel/blueprints'",
    ...ids.map(id => `import ${ident(id)} from './${id}.json'`),
    '',
    'export const BLUEPRINT_FILES: Readonly<Record<string, BlueprintDef>> = {',
    ...ids.map(id => `  ${JSON.stringify(id)}: ${ident(id)} as BlueprintDef,`),
    '}',
    '',
  ].join('\n')
}

/** Rewrite the index from the directory. Returns the ids it wrote. Idempotent: same input, same bytes. */
export function writeIndex(dir: string = BLUEPRINT_DIR, file: string = INDEX_FILE): string[] {
  const ids = blueprintFileIds(dir)
  const next = renderIndex(ids)
  let cur = ''
  try { cur = readFileSync(file, 'utf-8') } catch { /* first run */ }
  if (cur !== next) writeFileSync(file, next)
  return ids
}
