// GENERATED by data/blueprints/gen-index.ts — do not edit. Regenerated at prebuild and on every save.
import type { BlueprintDef } from '../../voxel/blueprints'
import bp_hazel_carpentry from './hazel_carpentry.json'
import bp_sparring_ring from './sparring_ring.json'

export const BLUEPRINT_FILES: Readonly<Record<string, BlueprintDef>> = {
  "hazel_carpentry": bp_hazel_carpentry as BlueprintDef,
  "sparring_ring": bp_sparring_ring as BlueprintDef,
}
