#!/usr/bin/env bash
# The bush FAMILY, and the recipes that make each one — run this, never blender by hand.
#
# ── ★ WHY THE DIALS LIVE HERE AND NOT IN A SHELL HISTORY ──────────────────────────────────────
# `sunfruit-bush.py` is one script for the whole family; what separates a sunfruit from a moonberry
# is the env below. Left in somebody's terminal, those numbers are the only copy of "what this
# plant IS", and the next re-bake quietly produces a different plant. This file is the recipe.
#
# ★ THE BAKE IS REPRODUCIBLE, AND IT WAS NOT UNTIL 2026-09-22. The per-vertex jitter used Python's
# `hash()` on tuples containing strings, which is randomised PER PROCESS — so the same script at
# the same SEED produced a different bush every run, and the mesh Alex approved could not be
# regenerated by anyone. `shash()` (crc32) fixed it; two consecutive runs are now byte-identical,
# which is what makes a look-approval mean something.
#
# ★ CANON DREW THE DIFFERENCES (`CANON/world/cuisine.md` › ★ ATHER FRUIT, ruled 2026-08-22):
#   Sunfruit  — "A warm golden FRUIT that glows faintly"  → singular, few, big, sits ON the crown
#   Moonberry — "Cool blue BERRIES that shimmer in low light" → plural, many, small, HANGING
# and they never stand side by side (sunfruit: meadow + basin, open sun · moonberry: woodland +
# shore, shade and damp), so the silhouettes answer the ground: a sun plant is a compact dome, a
# shade plant is low and broad because it is reaching.
#
#   ./scripts/models/bake-bushes.sh          # both, glb + previews + the TS modules
set -euo pipefail
cd "$(dirname "$0")/../.."
BLENDER=${BLENDER:-/opt/blender/blender}
OUT=public/models/flora
# 360 leaf triangles, not 720: the wild pool carries hundreds of these (measured 261k tris of a
# 397k frame undecimated) and Alex's desktop is an Intel UHD 630. See GBOARD's budget rule.
BUDGET=${DECIMATE_TRIS:-360}
# ⚠ The bloom bush is smaller than a fruit bush and carries 12 flat heads, so it takes a tighter
# leaf budget of its own — see its recipe below.

echo "── sunfruit: a compact dome, few big fruit on the crown"
NAME=sunfruit-bush SEED=1 \
  N_FRUIT=10 FRUIT_R_MIN=0.05 FRUIT_R_MAX=0.07 FRUIT_DROOP=0 FRUIT_FROM_TIER=1 \
  LEAF_RGB=0.22,0.50,0.16 FRUIT_RGB=1.0,0.74,0.10 \
  TARGET_W=1.0 TARGET_H=0.9 DECIMATE_TRIS=$BUDGET OUT=$OUT \
  "$BLENDER" -b -P scripts/models/sunfruit-bush.py | grep -E 'tris|FRUIT count|WROTE'

echo "── moonberry: low and broad, many small berries over the shoulders"
NAME=moonberry-bush SEED=7 \
  TIERS='[[5,0.24,0.16,0.31],[4,0.20,0.30,0.26]]' \
  N_FRUIT=14 FRUIT_R_MIN=0.048 FRUIT_R_MAX=0.062 FRUIT_DROOP=0.5 FRUIT_FROM_TIER=0 \
  LEAF_RGB=0.384,0.659,0.573 FRUIT_RGB=0.424,0.722,0.941 \
  TARGET_W=1.0 TARGET_H=0.62 DECIMATE_TRIS=$BUDGET OUT=$OUT \
  "$BLENDER" -b -P scripts/models/sunfruit-bush.py | grep -E 'TIERS|tris|FRUIT count|WROTE'

echo "── bloom bush: a flowering clump at a drift edge, blooms as flat faces"
# ⚠ NOT A FRUIT BUSH, AND NOT A SPECIES EITHER. `BLOOM_BUSH` is one of three DRAW FORMS of
# `MAT.FLOWER` (`flora.ts` › flowerForm): drift core -> a carpet, drift EDGE -> this clump, open
# ground -> a single stem. So it is one bake tinted per instance (body = the ground's green, heads
# = HEAD_TINTS), never a per-material pair like the sunfruit/moonberry split.
# FRUIT_FLATTEN 0.3 is what makes it flower rather than fruit: a berry is a ball, a bloom is a face.
NAME=bloom-bush SEED=3 \
  TIERS='[[5,0.22,0.14,0.30],[3,0.16,0.26,0.25]]' \
  N_FRUIT=12 FRUIT_R_MIN=0.075 FRUIT_R_MAX=0.095 FRUIT_FLATTEN=0.3 FRUIT_DROOP=0.15 FRUIT_FROM_TIER=0 \
  LEAF_RGB=0.26,0.52,0.20 FRUIT_RGB=0.92,0.82,0.98 \
  TARGET_W=0.85 TARGET_H=0.55 DECIMATE_TRIS=300 OUT=$OUT \
  "$BLENDER" -b -P scripts/models/sunfruit-bush.py | grep -E 'TIERS|tris|FRUIT count|WROTE'

echo "── baking all three to synchronous modules"
npx tsx scripts/bake-flora-model.mts $OUT/sunfruit-bush.glb  --out src/app/shimmer/voxel3d/models/sunfruit-bush.ts  --name sunfruitBush  --via "npm run bake:flora"
npx tsx scripts/bake-flora-model.mts $OUT/moonberry-bush.glb --out src/app/shimmer/voxel3d/models/moonberry-bush.ts --name moonberryBush --via "npm run bake:flora"
npx tsx scripts/bake-flora-model.mts $OUT/bloom-bush.glb     --out src/app/shimmer/voxel3d/models/bloom-bush.ts     --name bloomBush     --via "npm run bake:flora"
