# The CAULDRON — a thrown clay pot, as a sculpt instead of a stack of boxes.
#
# Run it through `scripts/models/bake-props.sh`, never blender by hand: the dials that make this
# pot THIS pot live there, and a number left in a terminal is the only copy of what the object is.
#
# ── ★ WHY A LATHE AND NOT A LUMP ──────────────────────────────────────────────────────────────
# `station-models/alchemy.ts` builds the cauldron from twelve axis-aligned boxes in four tiers,
# and the tiers are not a stylistic choice — they are hand-fitted to the TILE'S HORIZONTAL BANDS.
# `paintCauldron`'s side face is: a bright rim band in the top 12.5% (`size >> 3`), plain fired
# clay through the middle, and a dark stone HEARTH COURSE in the bottom 25% (`size / 4`), and a
# side face samples tile row (1 - local y). So the box model spends four tiers buying what a
# revolved profile gets continuously and for free: a pot that darkens into its hearth ring at the
# foot and brightens at the lip, with no step where one tier ends and the next begins.
#
# ── ★★ THE ONE CONSTRAINT THAT SHAPES THE WHOLE PROFILE: THE 30-DEGREE WALL ───────────────────
# The piece program does NOT blend three projections. It picks ONE with a hard branch on the
# dominant normal axis (`piece-mesh.ts`):
#
#     vec3 an = abs(vPNorm);
#     vec2 tileUv = an.y > 0.5 ? vPPos.xz : (an.x > 0.5 ? vec2(vPPos.z, -vPPos.y)
#                                                       : vec2(vPPos.x, -vPPos.y));
#     float layer  = an.y > 0.5 ? vLayerTop : vLayerSide;
#
# `an.y > 0.5` is a 60-degree CONE about vertical, not a dominant-axis test. So a facet wears the
# SIDE tile only while its normal is at least 60 degrees off vertical — i.e. while the WALL is
# within 30 degrees of vertical (|dr/dz| < 0.577). Past that it silently switches to the TOP tile
# AND to a plan projection, which on this block means the cauldron's dark water disc smeared over
# the pot's shoulder. Every rise in PROFILE below is under 0.5 on purpose; the assert at the end
# fails the bake if an edit breaks it. (The two faces that DO point up — the rim's annulus and the
# inner floor — are meant to, and the wiring gives the body a clay TOP tile so they read as clay.)
#
# ── ★ HAND-THROWN, NOT MANUFACTURED (canon) ───────────────────────────────────────────────────
# `design-briefs/shimmer-alchemy-vessels.md`: the Cauldron is FIRED CLAY and brews; "no metal
# anywhere in this world"; and the family law is *"Hand-blown, not manufactured. Slight asymmetry,
# an uneven base... Two vessels of the same kind are siblings, not clones."* The wobble below is
# that clause, and it is deliberately LOW-FREQUENCY — a circular blur over per-segment offsets, so
# the pot is a little out of round the way a thrown pot is, rather than lumpy the way noise is.
# High-frequency jitter would also fight the 30-degree rule: a wobble that moves a ring's radius
# faster than the profile does can tip a facet over the cone all by itself.
#
# ── ★ THE BAKE IS REPRODUCIBLE, AND THAT IS NOT FREE (jin/hub, 2026-09-22) ────────────────────
# Python's `hash()` is randomised per PROCESS for anything containing a string, so a script that
# jitters by `hash()` produces a different mesh every run and the object a human approved cannot
# be regenerated by anyone, including itself. `shash()` is crc32 and is stable across processes,
# machines and Python versions. NEVER use `hash()` here.
#
#   env: NAME · SEED · SEGMENTS (radial) · WOBBLE · LEAN · BREW_Z · BREW_R · OUT
#        PREVIEW_ONLY=1 to skip the glb · STATS_ONLY=1 to stop before the renders
import bpy, bmesh, math, os, zlib

NAME       = os.environ.get('NAME', 'cauldron')
SEED       = int(os.environ.get('SEED', '3'))
SEGMENTS   = int(os.environ.get('SEGMENTS', '24'))    # radial divisions — the silhouette's roundness
WOBBLE     = float(os.environ.get('WOBBLE', '0.016')) # out-of-round, in blocks, at the belly
LEAN       = float(os.environ.get('LEAN', '0.008'))   # the throw is a hair off plumb
FEET       = int(os.environ.get('FEET', '0'))         # 0 = the pot stands on its hearth-wide foot
FOOT_H     = float(os.environ.get('FOOT_H', '0.125'))  # only read when FEET > 0
BREW_Z     = float(os.environ.get('BREW_Z', '0.875')) # the liquid surface (the box model's 0.88)
BREW_R     = float(os.environ.get('BREW_R', '0.275'))
RES        = int(os.environ.get('RES', '560'))
OUT        = os.environ.get('OUT', 'public/models/props')
# ⚠ PREVIEWS DO NOT GO NEXT TO THE GLB. A bake writes them every run, and an untracked file under
# `public/` fails `coord build` for EVERY lane — it blocked hub's deploy the first time this ran.
# The glb is a committed source artifact; a preview is evidence for one look call and is scratch.
PREVIEW_OUT = os.environ.get('PREVIEW_OUT', 'scripts/.scratch/props')
PREVIEW_ONLY = os.environ.get('PREVIEW_ONLY') == '1'
STATS_ONLY   = os.environ.get('STATS_ONLY') == '1'

os.makedirs(OUT, exist_ok=True)
os.makedirs(PREVIEW_OUT, exist_ok=True)

# PROFILE is authored in POT SPACE (z from 0 at the pot's own floor to 1 at its lip) and mapped
# into the cell. With feet the pot starts above them and the whole profile COMPRESSES, which
# steepens every wall — so the 30-degree check below runs on the MAPPED rings, never on PROFILE.
BASE_Z = FOOT_H if FEET > 0 else 0.0


def cell_z(z_pot):
    return BASE_Z + z_pot * (1.0 - BASE_Z)


# crc32 over a joined string: stable across processes, machines and Python versions, which is the
# whole reason it is not `hash()`. Same helper as `sunfruit-bush.py`.
def shash(*parts):
    return zlib.crc32('|'.join(str(p) for p in parts).encode())


def unit(*parts):
    """A stable value in [-1, 1] from the seeded hash."""
    return (shash(SEED, *parts) % 2000 - 1000) / 1000.0


# ── ★ THE HEARTH BAND — WHY THIS POT IS WIDE AT THE FLOOR ─────────────────────────────────────
# `paintCauldron` spends the side tile's BOTTOM 25% (`hearthH = size / 4`) on a dark stone course
# and calls it, in its own comment, *"the fire bed it stands on"*; `alchemy.ts` reads it the same
# way — *"a pot standing on its hearth ring"*. So the bottom quarter of this model is not the pot,
# it is the FIRE the pot sits in, and it wants to be wide, solid and low. The first cut ignored
# that: it tapered to r=0.215 at the floor and propped the result on four small feet, and the
# render was unmistakably an URN on pegs — narrow-footed, teetering, mass in the wrong half. The
# foot is now nearly as wide as the belly, the waist sits where the stone course ends (0.235
# against 0.25), and the widest point moved DOWN to 0.53, because a cauldron carries its mass low
# and a vase carries it high. The feet survive behind `FEET=4` rather than being deleted, because
# which of the two reads better on prod is Alex's call and not the script's.
#
# ── THE PROFILE ────────────────────────────────────────────────────────────────────────────────
# (radius, height) in CELL UNITS, traversed as one continuous outline: out along the base, up the
# outside, in across the rim, down the inside, in along the inner floor. That single traversal is
# what makes the winding come out right everywhere — outward normals on the outside, inward on the
# inside, up on the rim and the inner floor, down on the base — with no per-face special case.
#
# `w` is how much of WOBBLE this ring takes: the base and the lip stay nearly true (a pot that
# will not stand, or whose lip is visibly buckled, reads as broken rather than as handmade), the
# belly takes it all.
#                r      z      w
PROFILE = [
    (0.000, 0.000, 0.00),  # base, centre          — normal DOWN, on the floor
    (0.375, 0.000, 0.10),  # base, edge: WIDE. See THE HEARTH BAND above.
    (0.392, 0.055, 0.20),  # the foot swells       rise 0.309
    (0.368, 0.150, 0.35),  #                       rise 0.253
    (0.352, 0.235, 0.55),  # the waist             rise 0.188   <- the hearth band ends here (0.25)
    (0.378, 0.330, 0.75),  # the clay belly begins rise 0.274
    (0.408, 0.435, 0.92),  #                       rise 0.286
    (0.420, 0.530, 1.00),  # the widest, and LOW   rise 0.126   <- the belly
    (0.412, 0.620, 1.00),  #                       rise 0.089
    (0.385, 0.710, 0.95),  #                       rise 0.300
    (0.350, 0.795, 0.80),  # the shoulder draws in rise 0.412
    (0.326, 0.868, 0.55),  # the neck              rise 0.329
    (0.330, 0.918, 0.35),  # the lip flares        rise 0.080
    (0.348, 0.968, 0.18),  #                       rise 0.360
    (0.347, 1.000, 0.15),  # rim, outer edge       rise 0.031
    (0.295, 1.000, 0.15),  # rim, inner edge       — normal UP, the lip you look over
    (0.287, 0.930, 0.20),  # inside the lip
    (0.283, 0.870, 0.25),  # the inner wall
    (0.285, 0.820, 0.25),  # the inner wall's foot
    (0.000, 0.805, 0.00),  # inner floor, centre   — normal UP, under the brew
]

MAX_RISE = 0.5   # |dr/dz| — see THE 30-DEGREE WALL above. 0.577 is the cliff; 0.5 is the margin.


def smoothed_wobble():
    """Per-segment out-of-roundness, circularly blurred so it is low-frequency."""
    raw = [unit('wob', j) for j in range(SEGMENTS)]
    return [(raw[j - 1] + 2.0 * raw[j] + raw[(j + 1) % SEGMENTS]) / 4.0 for j in range(SEGMENTS)]


WOB = smoothed_wobble()


def ring(r, z_pot, w):
    """One ring of the lathe, wobbled and leaned. `z_pot` is pot space; the cell height is mapped."""
    z = cell_z(z_pot)
    out = []
    for j in range(SEGMENTS):
        th = 2.0 * math.pi * j / SEGMENTS
        rr = r + WOBBLE * w * WOB[j]
        # the lean grows with height and is a translation, not a shear: the pot is off plumb, not
        # squashed. Squared so the base stays put.
        t = z_pot ** 2
        out.append((rr * math.cos(th) + LEAN * t, rr * math.sin(th) + LEAN * 0.6 * t, z))
    return out


def lathe(profile):
    """Revolve the profile. Poles (r == 0) become fans; everything else becomes quads."""
    verts, faces = [], []
    rings = []
    for (r, z_pot, w) in profile:
        z = cell_z(z_pot)
        if r <= 1e-6:
            verts.append((LEAN * (z_pot ** 2), 0.0, z))
            rings.append(('pole', len(verts) - 1))
        else:
            base = len(verts)
            verts.extend(ring(r, z_pot, w))
            rings.append(('ring', base))
    for i in range(len(rings) - 1):
        (ka, a), (kb, b) = rings[i], rings[i + 1]
        for j in range(SEGMENTS):
            j2 = (j + 1) % SEGMENTS
            if ka == 'pole' and kb == 'ring':
                faces.append((a, b + j2, b + j))          # fan under the base
            elif ka == 'ring' and kb == 'pole':
                faces.append((a + j, a + j2, b))          # fan over the inner floor
            elif ka == 'ring' and kb == 'ring':
                faces.append((a + j, a + j2, b + j2))     # the band, two triangles
                faces.append((a + j, b + j2, b + j))
    return verts, faces


def foot(cx, cy, k):
    """One stubby splayed foot. Six sides, a touch wider at the floor than where it meets the pot."""
    verts, faces = [], []
    r_lo = 0.082 + 0.010 * unit('foot-lo', k)
    r_hi = 0.066 + 0.008 * unit('foot-hi', k)
    spin = 0.22 * unit('foot-spin', k)
    top = FOOT_H * 1.04   # a hair into the pot's floor, so no seam opens between them
    for (r, z) in ((r_lo, 0.0), (r_hi, top)):
        for j in range(6):
            th = 2.0 * math.pi * j / 6 + spin
            verts.append((cx + r * math.cos(th), cy + r * math.sin(th), z))
    for j in range(6):
        j2 = (j + 1) % 6
        faces.append((j, j2, 6 + j2))
        faces.append((j, 6 + j2, 6 + j))
    faces.append((0, 2, 1)); faces.append((0, 3, 2)); faces.append((0, 4, 3)); faces.append((0, 5, 4))
    return verts, faces


def disc(r, z, n):
    """A flat n-gon facing up — the liquid's surface."""
    verts = [(0.0, 0.0, z)]
    for j in range(n):
        th = 2.0 * math.pi * j / n
        verts.append((r * math.cos(th), r * math.sin(th), z))
    faces = [(0, 1 + j, 1 + (j + 1) % n) for j in range(n)]
    return verts, faces


def mesh_object(name, verts, faces):
    me = bpy.data.meshes.new(name)
    me.from_pydata(verts, [], faces)
    me.validate()
    me.update()
    ob = bpy.data.objects.new(name, me)
    bpy.context.collection.objects.link(ob)
    # Flat shading, always: the world draws these flatShaded and derives normals from the
    # positions, so a smooth-shaded source is a lie the bake would throw away anyway.
    for p in me.polygons:
        p.use_smooth = False
    return ob


def merge(*pieces):
    verts, faces = [], []
    for (v, f) in pieces:
        base = len(verts)
        verts.extend(v)
        faces.extend([tuple(i + base for i in tri) for tri in f])
    return verts, faces


# ── BUILD ──────────────────────────────────────────────────────────────────────────────────────
bpy.ops.wm.read_factory_settings(use_empty=True)

pot = lathe(PROFILE)
feet = [foot(0.24 * math.cos(math.pi / 4 + k * math.pi / 2),
             0.24 * math.sin(math.pi / 4 + k * math.pi / 2), k) for k in range(FEET)]
body = mesh_object('Body', *merge(pot, *feet))
brew = mesh_object('Brew', *disc(BREW_R, BREW_Z, SEGMENTS))

# ── THE CONTRACT, CHECKED HERE SO A BAD EDIT CANNOT SHIP ───────────────────────────────────────
# 1. Every part stays inside the unit cell. The cell is what you collide with and mine, and a model
#    that leaks into the neighbour is the "invisible wall" failure `pieces.ts` warns of.
for ob in (body, brew):
    xs = [v.co[0] for v in ob.data.vertices]
    ys = [v.co[1] for v in ob.data.vertices]
    zs = [v.co[2] for v in ob.data.vertices]
    assert max(map(abs, xs)) <= 0.5 and max(map(abs, ys)) <= 0.5, \
        '%s leaves the cell in plan: x %.3f y %.3f' % (ob.name, max(map(abs, xs)), max(map(abs, ys)))
    assert min(zs) >= -1e-6 and max(zs) <= 1.0 + 1e-6, \
        '%s leaves the cell in height: %.3f..%.3f' % (ob.name, min(zs), max(zs))
    print('%-5s bounds  x %+.3f..%+.3f  y %+.3f..%+.3f  z %+.3f..%+.3f  tris %d'
          % (ob.name, min(xs), max(xs), min(ys), max(ys), min(zs), max(zs), len(ob.data.polygons)))

# 2. ★ THE 30-DEGREE WALL. Every rise in the profile stays under the cone, INCLUDING the wobble
#    at its worst — two adjacent segments pushed opposite ways move a facet's slope more than the
#    profile alone says. Checked against the real rings, not against PROFILE's nominal radii.
worst = (0.0, None)
for i in range(len(PROFILE) - 1):
    (r0, zp0, w0), (r1, zp1, w1) = PROFILE[i], PROFILE[i + 1]
    z0, z1 = cell_z(zp0), cell_z(zp1)
    if r0 <= 1e-6 or r1 <= 1e-6 or abs(z1 - z0) < 1e-6:
        continue                                  # a pole fan, or a horizontal face that MEANS to face up
    for j in range(SEGMENTS):
        a = r0 + WOBBLE * w0 * WOB[j]
        b = r1 + WOBBLE * w1 * WOB[j]
        rise = abs((b - a) / (z1 - z0))
        if rise > worst[0]:
            worst = (rise, 'profile %d->%d seg %d' % (i, i + 1, j))
print('worst wall rise |dr/dz| = %.3f at %s  (cliff 0.577, budget %.3f)' % (worst[0], worst[1], MAX_RISE))
assert worst[0] <= MAX_RISE, \
    'a wall rises %.3f at %s — past 0.5 it nears the 60-degree cone and the facet flips to the TOP tile' % worst

print('TRIS body %d  brew %d  total %d'
      % (len(body.data.polygons), len(brew.data.polygons),
         len(body.data.polygons) + len(brew.data.polygons)))

# ── EXPORT ─────────────────────────────────────────────────────────────────────────────────────
if not PREVIEW_ONLY:
    glb = os.path.join(OUT, NAME + '.glb')
    bpy.ops.object.select_all(action='DESELECT')
    body.select_set(True)
    brew.select_set(True)
    bpy.ops.export_scene.gltf(filepath=glb, use_selection=True, export_apply=True,
                              export_yup=True, export_format='GLB')
    print('WROTE', glb, os.path.getsize(glb), 'bytes')

if STATS_ONLY:
    import sys
    sys.exit(0)

# ── PREVIEW RENDERS ────────────────────────────────────────────────────────────────────────────
# ⚠ A render is the WRONG instrument for a final look call (the 09-22 bush lesson: at 360 tris the
# beauty render looked flatter than the game did, because the game draws the thing 40px tall). It
# is the right instrument for the question it IS asked here — is the silhouette a POT — before a
# four-minute prod round trip. The block's real tiles are not on it; the game is where those land.
def mat(name, rgb, rough=0.85):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    b = m.node_tree.nodes['Principled BSDF']
    b.inputs['Base Color'].default_value = (*rgb, 1)
    b.inputs['Roughness'].default_value = rough
    return m


body.data.materials.append(mat('Clay', (0.54, 0.32, 0.21)))
brew.data.materials.append(mat('Water', (0.18, 0.23, 0.27), rough=0.25))

scn = bpy.context.scene
scn.render.engine = 'CYCLES'
scn.cycles.samples = 48
scn.cycles.device = 'CPU'
scn.render.resolution_x = RES
scn.render.resolution_y = RES
scn.world = bpy.data.worlds.new('W')
scn.world.use_nodes = True
scn.world.node_tree.nodes['Background'].inputs['Color'].default_value = (0.09, 0.10, 0.13, 1)

bpy.ops.mesh.primitive_plane_add(size=8, location=(0, 0, 0))
bpy.context.object.data.materials.append(mat('Ground', (0.14, 0.15, 0.13), rough=1.0))

target = bpy.data.objects.new('Target', None)
bpy.context.collection.objects.link(target)
target.location = (0, 0, 0.55)


def add_cam(name, loc):
    bpy.ops.object.camera_add(location=loc)
    cam = bpy.context.object
    cam.name = name
    c = cam.constraints.new('TRACK_TO')
    c.target = target
    c.track_axis = 'TRACK_NEGATIVE_Z'
    c.up_axis = 'UP_Y'
    return cam


bpy.ops.object.light_add(type='SUN', location=(3, -2, 6))
bpy.context.object.data.energy = 3.2
bpy.ops.object.light_add(type='AREA', location=(-3, -1, 3))
bpy.context.object.data.energy = 180

# Standing over it — the angle a player actually brews from.
scn.camera = add_cam('CamQuarter', (1.35, -1.7, 1.45))
scn.render.filepath = os.path.join(PREVIEW_OUT, NAME + '_preview.png')
bpy.ops.render.render(write_still=True)
print('WROTE preview (3/4)')

# Eye level, straight on — the silhouette test.
scn.camera = add_cam('CamSide', (0.02, -1.9, 0.52))
scn.render.filepath = os.path.join(PREVIEW_OUT, NAME + '_preview_side.png')
bpy.ops.render.render(write_still=True)
print('WROTE preview (side)')
