// GENERATED by scripts/spirit-art.mts — do not edit by hand.
//
// Keys: '<species>' base · '<species>:<element>' second form · '<species>:<element>:<branch>'
// awakened. Derived from the three lock ledgers in /root/athernyx; `spirit-art.test.ts` re-derives
// this and goes red when a ledger gains a lock that has not been regenerated here, so a stale
// manifest cannot pass as a complete one.
//
// ⚠ ONLY LEDGER-LOCKED ART REACHES THIS FILE. The concept renders these were riffed from are
// non-commercial and must never ship; the generator refuses a source under a concept directory.

/** Portrait path by form key, or undefined when that form's art is not locked yet. */
export const SPIRIT_ART: Readonly<Record<string, string>> = Object.freeze({
  "axolotl": "/spirits/grimoire/axolotl.webp",
  "axolotl:earth": "/spirits/grimoire/axolotl-earth.webp",
  "axolotl:mana": "/spirits/grimoire/axolotl-mana.webp",
  "axolotl:storm": "/spirits/grimoire/axolotl-storm.webp",
  "axolotl:water": "/spirits/grimoire/axolotl-water.webp",
  "bat": "/spirits/grimoire/bat.webp",
  "bat:earth": "/spirits/grimoire/bat-earth.webp",
  "bat:mana": "/spirits/grimoire/bat-mana.webp",
  "bat:storm": "/spirits/grimoire/bat-storm.webp",
  "bat:water": "/spirits/grimoire/bat-water.webp",
  "firefly": "/spirits/grimoire/firefly.webp",
  "firefly:earth": "/spirits/grimoire/firefly-earth.webp",
  "firefly:mana": "/spirits/grimoire/firefly-mana.webp",
  "firefly:storm": "/spirits/grimoire/firefly-storm.webp",
  "firefly:water": "/spirits/grimoire/firefly-water.webp",
  "fox": "/spirits/grimoire/fox.webp",
  "fox:earth": "/spirits/grimoire/fox-earth.webp",
  "fox:mana": "/spirits/grimoire/fox-mana.webp",
  "fox:mana:alpha": "/spirits/grimoire/fox-mana-alpha.webp",
  "fox:mana:beta": "/spirits/grimoire/fox-mana-beta.webp",
  "fox:mana:delta": "/spirits/grimoire/fox-mana-delta.webp",
  "fox:mana:gamma": "/spirits/grimoire/fox-mana-gamma.webp",
  "fox:storm": "/spirits/grimoire/fox-storm.webp",
  "fox:water": "/spirits/grimoire/fox-water.webp",
  "frog": "/spirits/grimoire/frog.webp",
  "frog:earth": "/spirits/grimoire/frog-earth.webp",
  "frog:mana": "/spirits/grimoire/frog-mana.webp",
  "frog:storm": "/spirits/grimoire/frog-storm.webp",
  "frog:water": "/spirits/grimoire/frog-water.webp",
  "hummingbird": "/spirits/grimoire/hummingbird.webp",
  "hummingbird:earth": "/spirits/grimoire/hummingbird-earth.webp",
  "hummingbird:mana": "/spirits/grimoire/hummingbird-mana.webp",
  "hummingbird:storm": "/spirits/grimoire/hummingbird-storm.webp",
  "hummingbird:water": "/spirits/grimoire/hummingbird-water.webp",
  "owl": "/spirits/grimoire/owl.webp",
  "owl:earth": "/spirits/grimoire/owl-earth.webp",
  "owl:mana": "/spirits/grimoire/owl-mana.webp",
  "owl:storm": "/spirits/grimoire/owl-storm.webp",
  "owl:water": "/spirits/grimoire/owl-water.webp",
  "rabbit": "/spirits/grimoire/rabbit.webp",
  "rabbit:earth": "/spirits/grimoire/rabbit-earth.webp",
  "rabbit:mana": "/spirits/grimoire/rabbit-mana.webp",
  "rabbit:storm": "/spirits/grimoire/rabbit-storm.webp",
  "rabbit:water": "/spirits/grimoire/rabbit-water.webp",
  "turtle": "/spirits/grimoire/turtle.webp",
  "turtle:earth": "/spirits/grimoire/turtle-earth.webp",
  "turtle:mana": "/spirits/grimoire/turtle-mana.webp",
  "turtle:storm": "/spirits/grimoire/turtle-storm.webp",
  "turtle:water": "/spirits/grimoire/turtle-water.webp",
  "water-bear": "/spirits/grimoire/water-bear.webp",
  "water-bear:earth": "/spirits/grimoire/water-bear-earth.webp",
  "water-bear:mana": "/spirits/grimoire/water-bear-mana.webp",
  "water-bear:storm": "/spirits/grimoire/water-bear-storm.webp",
  "water-bear:water": "/spirits/grimoire/water-bear-water.webp",
})

/** Every form key that has locked art. */
export const SPIRIT_ART_KEYS: readonly string[] = Object.freeze(Object.keys(SPIRIT_ART))
