'use client'

// The voxel world you can walk, mine and build in. A test bed, on its own route, on purpose.
//
// ⚠ NOT WIRED INTO Shimmer3D, DELIBERATELY. That file is ~5,900 lines of the live game (mortal
// side, holds, Crucible, and the warp/mount path that produced four bugs on 08-06) while this walks
// a DIFFERENT WORLD MODEL — no zones, no tiles, no warps. Integration is a later decision.
//
// ★ GENERATION RUNS IN A WORKER; MESHING AND EDITS STAY HERE. That split is deliberate. Mining
// edits a voxel and immediately re-meshes, so this thread has to own the Columns anyway — shipping
// one across the boundary per edit would cost more than it saves. The worker does the expensive,
// order-independent half (~109ms/chunk of noise, carving and ore) and hands back packed voxels;
// this thread wraps them into a Column and meshes (~47ms).
//
// ⚠ The worker URL is CONTENT-HASHED (`worker-url.ts`, generated by scripts/build-worker.mjs).
// It shipped as a fixed `/voxel-gen.worker.js` first, and /public caching pinned the browser to the
// FIRST build through every later deploy — a worker that answered old messages and ignored new ones,
// which reads exactly like a worker that half-works. Do not un-hash this.

import { useRef, useMemo, useState, useEffect, useCallback } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { PointerLockControls } from '@react-three/drei'
import * as THREE from 'three'
import { SECTION, DEFAULT_COLUMN, Column, Stage, makeColumn, meshColumn, refreshUniform } from '../voxel/column'
import { VOXEL_WORKER_URL } from '../../../workers/worker-url'
import { createMeshScratch } from '../voxel/greedy'
import { columnHeight } from '../voxel/height'
import { AIR } from '../voxel/section'
import { MAT } from '../voxel/depth'
import { raycast, tickBreak, dropsFor, type BreakState } from '../voxel/mine'
import { spawnDrop, tickDrops, type Drop } from '../voxel/drops'
import { blockDef, materialForItem, type BlockSkill } from '../voxel/registry'
import { toGeometry, createVoxelMaterial } from './mesh-bridge'
import { buildAttrs, MATERIAL_COLOR } from './attrs'
import { createInventory, addItems, removeItems, countItem, type Inventory } from '../engine/inventory'

const SEED = 1337
const H = DEFAULT_COLUMN.worldHeight
const RADIUS = 6
const REACH = 6            // how far you can mine or place, in voxels
const key = (cx: number, cz: number) => `${cx},${cz}`

interface Slot { itemId: string; count: number }

export default function VoxelWorld() {
  const [stats, setStats] = useState('generating…')
  const [pos, setPos] = useState('')
  const [hotbar, setHotbar] = useState<Slot[]>([])
  const [sel, setSel] = useState(0)
  const [tier, setTier] = useState(1)
  const [look, setLook] = useState<{ name: string; progress: number; refused: boolean } | null>(null)
  const worker = useRef<Worker | null>(null)
  const incoming = useRef<{ cx: number; cz: number; voxels: Uint16Array }[]>([])
  const inflight = useRef(0)

  useEffect(() => {
    let w: Worker
    try { w = new Worker(VOXEL_WORKER_URL) }
    catch (e) { setStats(`worker failed to start: ${String(e)} — main thread`); return }
    // Handler BEFORE post: assigning onmessage after postMessage races the first reply, and reads
    // as "the worker never answered".
    w.onmessage = (e) => {
      const m = e.data
      if (m.type === 'column') incoming.current.push({ cx: m.cx, cz: m.cz, voxels: m.voxels })
      else if (m.type === 'done') inflight.current = Math.max(0, inflight.current - 1)
    }
    w.onerror = (ev) => { setStats(`worker error: ${ev.message} — falling back to main thread`); worker.current = null }
    w.postMessage({ type: 'init', seed: SEED })
    worker.current = w
    return () => { w.terminate(); worker.current = null }
  }, [])

  // ★ THE SPIKE IS CANON, NOT INVENTED. `engine/tools.ts` rules blades→forestry,
  // spikes→prospecting, rinsticks→rinning, with a basic Greg-given tool that never breaks. So
  // "what do I mine rock with" already had an answer and nothing here needed naming.
  const toolTier = useRef(1)
  const toolSkill = useRef<BlockSkill>('prospecting')
  const inv = useRef<Inventory>(createInventory())

  const refreshHotbar = useCallback(() => {
    const counts = new Map<string, number>()
    for (const s of inv.current.slots) if (s) counts.set(s.itemId, (counts.get(s.itemId) ?? 0) + s.count)
    setHotbar([...counts].map(([itemId, count]) => ({ itemId, count })).slice(0, 8))
  }, [])

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const n = Number(e.key)
      if (n >= 1 && n <= 8) setSel(n - 1)
      // Tool tier is a debug lever so the tier GATE can be felt in ten seconds: a tier-1 spike
      // REFUSES pure core, and that should be provable without crafting your way up first.
      if (e.code === 'BracketRight') { toolTier.current = Math.min(3, toolTier.current + 1); setTier(toolTier.current) }
      if (e.code === 'BracketLeft') { toolTier.current = Math.max(1, toolTier.current - 1); setTier(toolTier.current) }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  return (
    <div className="fixed inset-0 bg-[#0b0d14]">
      <Canvas camera={{ fov: 75, near: 0.1, far: 600 }} shadows={false}>
        <color attach="background" args={['#8fb7d9']} />
        <fog attach="fog" args={['#8fb7d9', 80, 200]} />
        <hemisphereLight args={['#cfe6ff', '#3b3a4a', 1.5]} />
        <directionalLight position={[80, 200, 40]} intensity={1.5} />
        <ambientLight intensity={0.4} />
        <World
          inv={inv} toolTier={toolTier} toolSkill={toolSkill}
          selItem={hotbar[sel]?.itemId ?? null}
          onStats={setStats} onPos={p => setPos(`x ${p.x.toFixed(0)}  y ${p.y.toFixed(0)}  z ${p.z.toFixed(0)}`)}
          onLook={setLook} onInvChange={refreshHotbar}
          worker={worker} incoming={incoming} inflight={inflight}
        />
        <PointerLockControls />
      </Canvas>
      <Hud stats={stats} pos={pos} look={look} hotbar={hotbar} sel={sel} tier={tier} />
    </div>
  )
}

function Hud({ stats, pos, look, hotbar, sel, tier }: {
  stats: string; pos: string
  look: { name: string; progress: number; refused: boolean } | null
  hotbar: Slot[]; sel: number; tier: number
}) {
  return (
    <>
      <div className="absolute top-3 left-3 text-[11px] font-mono text-white/80 bg-black/45 rounded px-2.5 py-1.5 leading-relaxed pointer-events-none">
        <div className="text-white/95 font-semibold tracking-wide">SHIMMER · VOXEL TEST BED</div>
        <div>{pos}</div>
        <div className="text-white/55">{stats}</div>
        <div className="mt-1 text-white/45">click to look · WASD · space · shift run · F fly</div>
        <div className="text-white/45">hold LMB mine · RMB place · 1-8 slot · [ ] spike tier</div>
      </div>

      {look && (
        <div className="absolute left-1/2 top-[56%] -translate-x-1/2 text-center pointer-events-none">
          <div className={`text-[11px] font-mono tracking-wide ${look.refused ? 'text-red-300' : 'text-white/85'}`}>
            {look.name}{look.refused && ' — spike too weak'}
          </div>
          {look.progress > 0 && (
            <div className="mt-1 w-28 h-1 bg-black/50 rounded overflow-hidden mx-auto">
              <div className="h-full bg-amber-300" style={{ width: `${Math.min(100, look.progress * 100)}%` }} />
            </div>
          )}
        </div>
      )}

      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-1 h-1 rounded-full bg-white/80 pointer-events-none" />

      {/* Colour swatches stand in for item art — the registry maps materials to tiles.ts later. */}
      <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-1.5 pointer-events-none">
        {Array.from({ length: 8 }, (_, i) => {
          const s = hotbar[i]
          const mat = s ? materialForItem(s.itemId) : undefined
          const swatch = mat !== undefined ? `#${(MATERIAL_COLOR[mat] ?? 0x888888).toString(16).padStart(6, '0')}` : undefined
          return (
            <div key={i} className={`w-12 h-12 rounded border-2 flex flex-col items-center justify-center text-[9px] font-mono
              ${i === sel ? 'border-amber-300 bg-black/60' : 'border-white/20 bg-black/40'}`}>
              {s ? (
                <>
                  <div className="w-5 h-5 rounded-sm border border-white/25" style={{ background: swatch ?? '#6b7280' }} />
                  <div className="text-white/80 mt-0.5">{s.count}</div>
                </>
              ) : <span className="text-white/25">{i + 1}</span>}
            </div>
          )
        })}
      </div>
      <div className="absolute bottom-[4.6rem] left-1/2 -translate-x-1/2 text-[10px] font-mono text-white/50 pointer-events-none">
        spike tier {tier}
      </div>
    </>
  )
}

const SOLID_EXCEPT = new Set<number>([AIR, MAT.WATER])
const isSolid = (m: number) => !SOLID_EXCEPT.has(m)

function World({ inv, toolTier, toolSkill, selItem, onStats, onPos, onLook, onInvChange, worker, incoming, inflight }: {
  inv: React.RefObject<Inventory>
  toolTier: React.RefObject<number>
  toolSkill: React.RefObject<BlockSkill>
  selItem: string | null
  onStats: (s: string) => void
  onPos: (p: THREE.Vector3) => void
  onLook: (l: { name: string; progress: number; refused: boolean } | null) => void
  onInvChange: () => void
  worker: React.RefObject<Worker | null>
  incoming: React.RefObject<{ cx: number; cz: number; voxels: Uint16Array }[]>
  inflight: React.RefObject<number>
}) {
  const { camera, gl } = useThree()
  const group = useRef<THREE.Group>(null)
  const highlight = useRef<THREE.LineSegments>(null)
  const material = useMemo(() => createVoxelMaterial(), [])
  const scratch = useMemo(() => createMeshScratch(SECTION), [])
  const cols = useRef(new Map<string, Column>())
  const drawn = useRef(new Map<string, THREE.Mesh>())
  const breaking = useRef<BreakState | null>(null)
  const drops = useRef<Drop[]>([])
  const dropMeshes = useRef(new Map<number, THREE.Mesh>())
  /**
   * ★ ONE GEOMETRY AND A MATERIAL CACHE FOR EVERY DROP — NOT ONE EACH.
   *
   * The first version built `new THREE.BoxGeometry` AND `new THREE.MeshLambertMaterial` per dropped
   * item. A material is a SHADER PROGRAM; a few hundred drops is a few hundred programs plus a few
   * hundred buffers, and Chrome responds by losing the WebGL context and then BLOCKING the page
   * from creating another one: "Web page caused context loss and was blocked", after which the
   * whole canvas is black and no amount of reloading helps until the tab is closed.
   *
   * This is the exact failure `mesh-bridge.ts` warns about for chunk meshes — "a material per chunk
   * is a shader program per chunk, and that is how a voxel renderer dies" — and I wrote that
   * warning and then did it anyway in the drop path. Geometry is shared outright; materials are
   * cached by colour, so the ceiling is the number of distinct block colours, not the number of
   * items on the floor.
   */
  const dropGeo = useMemo(() => new THREE.BoxGeometry(0.28, 0.28, 0.28), [])
  const dropMats = useRef(new Map<number, THREE.Material>())
  const highlightGeo = useMemo(() => new THREE.EdgesGeometry(new THREE.BoxGeometry(1.002, 1.002, 1.002)), [])
  const dropGroup = useRef<THREE.Group>(null)
  const mouse = useRef({ left: false, right: false })
  const frame = useRef(0)
  const requested = useRef(new Set<string>())
  const settled = useRef(false)
  const vel = useRef(new THREE.Vector3())
  // ★ Scratch vectors, allocated ONCE. Four `new THREE.Vector3()` per frame is 240 objects/sec of
  // pure garbage — not a GPU leak, but exactly the GC pressure the mesher and carver were both
  // rewritten to avoid. Same rule, applied to the frame loop instead of the hot inner loop.
  const vAim = useRef(new THREE.Vector3())
  const vFwd = useRef(new THREE.Vector3())
  const vRight = useRef(new THREE.Vector3())
  const vWish = useRef(new THREE.Vector3())
  const UP = useMemo(() => new THREE.Vector3(0, 1, 0), [])
  const keys = useRef<Record<string, boolean>>({})
  const fly = useRef(false)
  const onGround = useRef(false)

  useEffect(() => {
    const kd = (e: KeyboardEvent) => { keys.current[e.code] = true; if (e.code === 'KeyF') fly.current = !fly.current }
    const ku = (e: KeyboardEvent) => { keys.current[e.code] = false }
    const md = (e: MouseEvent) => { if (e.button === 0) mouse.current.left = true; if (e.button === 2) mouse.current.right = true }
    const mu = (e: MouseEvent) => { if (e.button === 0) mouse.current.left = false; if (e.button === 2) mouse.current.right = false }
    const ctx = (e: Event) => e.preventDefault()
    window.addEventListener('keydown', kd); window.addEventListener('keyup', ku)
    window.addEventListener('mousedown', md); window.addEventListener('mouseup', mu)
    window.addEventListener('contextmenu', ctx)
    return () => {
      window.removeEventListener('keydown', kd); window.removeEventListener('keyup', ku)
      window.removeEventListener('mousedown', md); window.removeEventListener('mouseup', mu)
      window.removeEventListener('contextmenu', ctx)
    }
  }, [])

  useEffect(() => { camera.position.set(0.5, columnHeight(0, 0, SEED) + 2.6, 0.5) }, [camera])

  /** What is actually there. Unloaded reads as AIR — used for the raycast, so you can never target
   *  or mine a block that has not been generated. */
  // ★ EVERYTHING THIS COMPONENT ALLOCATES ON THE GPU IS RELEASED ON UNMOUNT. Without this, a
  // navigation away leaks every chunk geometry plus the shared material and drop resources — and a
  // page that leaks a full render's worth of buffers per visit is how the context gets lost in the
  // first place. The shared resources are disposed here and ONLY here, because disposing them
  // anywhere else would break every object still using them.
  useEffect(() => () => {
    for (const m of drawn.current.values()) m.geometry.dispose()
    drawn.current.clear()
    dropMeshes.current.clear()
    for (const m of dropMats.current.values()) m.dispose()
    dropMats.current.clear()
    dropGeo.dispose()
    highlightGeo.dispose()
    material.dispose()
  }, [dropGeo, highlightGeo, material])

  // ★ A LOST WEBGL CONTEXT MUST SAY SO. Chrome blocks a page that loses its context repeatedly, and
  // the result is a black canvas with the HUD still drawn on top — indistinguishable from a
  // generation failure, which is exactly why I hunted the mesher first when it happened. The block
  // is sticky for the life of the tab: reloading does not clear it, closing the tab does.
  useEffect(() => {
    const cv = gl.domElement
    const lost = (e: Event) => { e.preventDefault(); onStats('WEBGL CONTEXT LOST — close this tab and open a new one') }
    const restored = () => onStats('webgl context restored')
    cv.addEventListener('webglcontextlost', lost)
    cv.addEventListener('webglcontextrestored', restored)
    return () => { cv.removeEventListener('webglcontextlost', lost); cv.removeEventListener('webglcontextrestored', restored) }
  }, [gl, onStats])

  const voxel = useCallback((wx: number, wy: number, wz: number): number => {
    if (wy < 0 || wy >= H) return AIR
    const cx = Math.floor(wx / SECTION), cz = Math.floor(wz / SECTION)
    const c = cols.current.get(key(cx, cz))
    if (!c) return AIR
    return c.get(wx - cx * SECTION, wy, wz - cz * SECTION)
  }, [])

  /**
   * ★ COLLISION TREATS UNGENERATED SPACE AS SOLID, AND THAT IS THE WHOLE FIX FOR FALLING OFF THE
   * MAP. Sprinting is 22 units/s and generation is bounded, so a player outruns the load radius
   * routinely. With unloaded reading as AIR the floor simply is not there yet and you drop through
   * the world — which is what "I found a gap and fell off the map" actually was.
   *
   * Unknown terrain must BLOCK, never swallow. The worst case is standing still for a moment at the
   * edge of the world; the alternative is falling out of it. Note this deliberately differs from
   * `voxel` above: the raycast must NOT see phantom solids, or you would mine invisible blocks at
   * the frontier.
   */
  const voxelSolid = useCallback((wx: number, wy: number, wz: number): number => {
    if (wy < 0) return MAT.BEDROCK
    if (wy >= H) return AIR
    const cx = Math.floor(wx / SECTION), cz = Math.floor(wz / SECTION)
    const c = cols.current.get(key(cx, cz))
    if (!c) return MAT.BEDROCK          // not generated yet ⇒ stand on it, do not fall through it
    return c.get(wx - cx * SECTION, wy, wz - cz * SECTION)
  }, [])

  const remesh = useCallback((cx: number, cz: number) => {
    const g = group.current
    const c = cols.current.get(key(cx, cz))
    if (!g || !c) return
    const k = key(cx, cz)
    for (const [mk, m] of drawn.current) {
      if (!mk.startsWith(k + ':')) continue
      g.remove(m); m.geometry.dispose(); drawn.current.delete(mk)
    }
    for (const sm of meshColumn(c, {
      negX: cols.current.get(key(cx - 1, cz)) ?? null,
      posX: cols.current.get(key(cx + 1, cz)) ?? null,
      negZ: cols.current.get(key(cx, cz - 1)) ?? null,
      posZ: cols.current.get(key(cx, cz + 1)) ?? null,
    }, scratch)) {
      const mesh = new THREE.Mesh(toGeometry(buildAttrs(sm.mesh)), material)
      mesh.position.set(sm.wx, sm.wy, sm.wz)
      g.add(mesh)
      drawn.current.set(`${k}:${sm.index}`, mesh)
    }
  }, [material, scratch])

  /**
   * Write one voxel and repair the geometry.
   *
   * ★ THE NEIGHBOUR RE-MESH IS NOT OPTIONAL. Editing a voxel on a column's edge changes which faces
   * the NEIGHBOUR should draw — mine the last block of a column and, without this, the neighbour
   * keeps the wall it drew while that block still existed. It reads as an invisible pane you cannot
   * mine, sitting at exactly the seams a player walks along.
   *
   * `refreshUniform` matters for the same class of reason: the mesher's skip reads that table, and
   * a stale entry means dropped faces.
   */
  const setVoxel = useCallback((wx: number, wy: number, wz: number, mat: number) => {
    const cx = Math.floor(wx / SECTION), cz = Math.floor(wz / SECTION)
    const c = cols.current.get(key(cx, cz))
    if (!c) return
    const lx = wx - cx * SECTION, lz = wz - cz * SECTION
    const s = (wy / SECTION) | 0
    c.sections[s].set(lx, wy - s * SECTION, lz, mat)
    refreshUniform(c)
    remesh(cx, cz)
    if (lx === 0) remesh(cx - 1, cz)
    if (lx === SECTION - 1) remesh(cx + 1, cz)
    if (lz === 0) remesh(cx, cz - 1)
    if (lz === SECTION - 1) remesh(cx, cz + 1)
  }, [remesh])

  const blocked = useCallback((x: number, y: number, z: number) => {
    const y0 = Math.floor(y - 1.62), y1 = Math.floor(y - 1.62 + 1.75)
    for (let vy = y0; vy <= y1; vy++)
      for (const dx of [-0.3, 0.3]) for (const dz of [-0.3, 0.3])
        if (isSolid(voxelSolid(Math.floor(x + dx), vy, Math.floor(z + dz)))) return true
    return false
  }, [voxelSolid])

  useFrame((_, dtRaw) => {
    const dt = Math.min(dtRaw, 0.05)
    const g = group.current
    if (!g) return
    const p = camera.position
    const cx = Math.floor(p.x / SECTION), cz = Math.floor(p.z / SECTION)

    // ── adopt whatever the worker finished ───────────────────────────────────────────────────
    // Wrapping packed voxels into a Column is a view, not a copy: the sections point straight into
    // the transferred buffer, so adopting a generated column costs nothing.
    const t0 = performance.now()
    let adopted = 0
    while (incoming.current!.length && adopted < 2) {
      const { cx: gx, cz: gz, voxels } = incoming.current!.shift()!
      const col = new Column(gx * SECTION, gz * SECTION)
      const per = SECTION * SECTION * SECTION
      for (let i = 0; i < col.sections.length; i++) col.sections[i].data.set(voxels.subarray(i * per, (i + 1) * per))
      for (let z = 0; z < SECTION; z++) for (let x = 0; x < SECTION; x++)
        col.surface[z * SECTION + x] = columnHeight(gx * SECTION + x, gz * SECTION + z, SEED)
      refreshUniform(col)
      col.stage = Stage.Ready
      cols.current.set(key(gx, gz), col)
      remesh(gx, gz)
      for (const [ddx, ddz] of [[-1, 0], [1, 0], [0, -1], [0, 1]] as const)
        if (cols.current.has(key(gx + ddx, gz + ddz))) remesh(gx + ddx, gz + ddz)
      adopted++
    }

    // ── request what is missing, nearest first ───────────────────────────────────────────────
    const want: [number, number, number][] = []
    for (let dz = -RADIUS; dz <= RADIUS; dz++) for (let dx = -RADIUS; dx <= RADIUS; dx++) {
      const d = dx * dx + dz * dz
      if (d > RADIUS * RADIUS) continue
      const kk = key(cx + dx, cz + dz)
      if (!cols.current.has(kk) && !requested.current.has(kk)) want.push([d, cx + dx, cz + dz])
    }
    want.sort((a, b) => a[0] - b[0])
    const w = worker.current
    for (const [, gx, gz] of want) {
      if (w) {
        if (inflight.current! >= 4) break
        requested.current.add(key(gx, gz))
        inflight.current!++
        w.postMessage({ type: 'request', cx: gx, cz: gz })
      } else {
        // No worker (construction failed): generate here so the world still exists.
        if (performance.now() - t0 > 10) break
        requested.current.add(key(gx, gz))
        cols.current.set(key(gx, gz), makeColumn(gx * SECTION, gz * SECTION, SEED))
        remesh(gx, gz)
        for (const [ddx, ddz] of [[-1, 0], [1, 0], [0, -1], [0, 1]] as const)
          if (cols.current.has(key(gx + ddx, gz + ddz))) remesh(gx + ddx, gz + ddz)
      }
    }

    // Until the spawn column exists every lookup returns AIR, so gravity would drop the player
    // through a world that has not generated yet. Hold until there is ground beneath.
    if (!settled.current) {
      if (isSolid(voxel(0, Math.floor(p.y) - 3, 0))) settled.current = true   // real ground, not the phantom floor
      else { onPos(p); onStats(`${cols.current.size} columns · generating…`); return }
    }

    // ── movement ─────────────────────────────────────────────────────────────────────────────
    const k = keys.current
    const speed = (k.ShiftLeft ? 22 : 9) * (fly.current ? 2.2 : 1)
    const aim = vAim.current
    camera.getWorldDirection(aim)
    const fwd = vFwd.current.copy(aim); fwd.y = 0; fwd.normalize()
    const right = vRight.current.crossVectors(fwd, UP)
    const wish = vWish.current.set(0, 0, 0)
    if (k.KeyW) wish.add(fwd)
    if (k.KeyS) wish.sub(fwd)
    if (k.KeyD) wish.add(right)
    if (k.KeyA) wish.sub(right)
    if (wish.lengthSq() > 0) wish.normalize().multiplyScalar(speed)

    if (fly.current) {
      if (k.Space) wish.y += speed
      if (k.ControlLeft) wish.y -= speed
      p.addScaledVector(wish, dt)
    } else {
      vel.current.x = wish.x; vel.current.z = wish.z
      vel.current.y -= 28 * dt
      if (onGround.current && k.Space) vel.current.y = 9.2
      const nx = p.x + vel.current.x * dt
      if (!blocked(nx, p.y, p.z)) p.x = nx
      const nz = p.z + vel.current.z * dt
      if (!blocked(p.x, p.y, nz)) p.z = nz
      const ny = p.y + vel.current.y * dt
      if (!blocked(p.x, ny, p.z)) { p.y = ny; onGround.current = false }
      else { if (vel.current.y < 0) onGround.current = true; vel.current.y = 0 }
      if (p.y < -20) { p.set(0.5, columnHeight(0, 0, SEED) + 2.6, 0.5); settled.current = false }
    }

    // ── what are we looking at ───────────────────────────────────────────────────────────────
    const hit = raycast(p.x, p.y, p.z, aim.x, aim.y, aim.z, REACH, voxel)
    const hl = highlight.current
    if (hl) {
      hl.visible = !!hit
      if (hit) hl.position.set(hit.x + 0.5, hit.y + 0.5, hit.z + 0.5)
    }

    // ── mine ─────────────────────────────────────────────────────────────────────────────────
    if (hit && mouse.current.left) {
      const r = tickBreak(breaking.current, hit, dt, toolTier.current!, toolSkill.current!)
      breaking.current = r.state
      if (r.broken) {
        // ★ The block bursts into an ENTITY on the floor, it does not teleport into the satchel.
        // Straight-to-inventory works and feels like nothing happened; seeing the shard fall is
        // what tells the player the swing landed and what the vein actually yielded.
        for (const d of dropsFor(hit.material)) drops.current.push(spawnDrop(d.itemId, d.count, hit.x, hit.y, hit.z))
        setVoxel(hit.x, hit.y, hit.z, AIR)
        breaking.current = null
      }
    } else if (!mouse.current.left) {
      breaking.current = null
    }

    // ── place ────────────────────────────────────────────────────────────────────────────────
    if (hit && mouse.current.right && selItem) {
      const mat = materialForItem(selItem)
      // Refuse to place inside your own body — the classic way to entomb yourself.
      const inPlayer = Math.floor(p.x) === hit.px && Math.floor(p.z) === hit.pz
        && (Math.floor(p.y) === hit.py || Math.floor(p.y - 1.62) === hit.py)
      if (mat !== undefined && !inPlayer && countItem(inv.current!, selItem) > 0 && voxel(hit.px, hit.py, hit.pz) === AIR) {
        removeItems(inv.current!, selItem, 1)
        setVoxel(hit.px, hit.py, hit.pz, mat)
        onInvChange()
        mouse.current.right = false   // one block per click, not a firehose
      }
    }

    // ── dropped items ────────────────────────────────────────────────────────────────────────
    // Physics resolves against the voxel grid (not a heightfield), so a shard mined in a cave rests
    // on the cave floor rather than on the surface hundreds of blocks above it.
    if (drops.current.length) {
      const res = tickDrops(drops.current, dt, p.x, p.y - 0.8, p.z,
        (x, y, z) => isSolid(voxelSolid(x, y, z)))
      if (res.picked.length) {
        for (const it of res.picked) addItems(inv.current!, it.itemId, it.count)
        onInvChange()
      }
    }
    const dg = dropGroup.current
    if (dg) {
      const live = new Set<number>()
      for (const d of drops.current) {
        live.add(d.id)
        let m = dropMeshes.current.get(d.id)
        if (!m) {
          const mat = materialForItem(d.itemId)
          const colour = mat !== undefined ? (MATERIAL_COLOR[mat] ?? 0xcccccc) : 0xffd479
          let dm = dropMats.current.get(colour)
          if (!dm) {
            dm = new THREE.MeshLambertMaterial({ color: colour, emissive: colour, emissiveIntensity: 0.25 })
            dropMats.current.set(colour, dm)
          }
          m = new THREE.Mesh(dropGeo, dm)
          dg.add(m)
          dropMeshes.current.set(d.id, m)
        }
        // Bob and spin so a shard on a grey cave floor is findable rather than camouflaged.
        m.position.set(d.x, d.y + (d.resting ? 0.06 * Math.sin(d.age * 3) : 0), d.z)
        m.rotation.y = d.age * 1.6
      }
      for (const [id, m] of dropMeshes.current) {
        if (live.has(id)) continue
        // Geometry and material are SHARED — disposing them here would destroy every other drop's
        // rendering. Only the Mesh wrapper is thrown away.
        dg.remove(m)
        dropMeshes.current.delete(id)
      }
    }

    // ── HUD ──────────────────────────────────────────────────────────────────────────────────
    const def = hit ? blockDef(hit.material) : undefined
    onLook(hit && def
      ? {
          name: def.name,
          progress: breaking.current ? breaking.current.progress / breaking.current.required : 0,
          refused: mouse.current.left && !breaking.current && def.hardness !== Infinity,
        }
      : null)
    onPos(p)
    if (++frame.current % 10 === 0) {
      // ★ GPU RESOURCE COUNTS IN THE HUD. A leak used to announce itself by Chrome blocking the
      // context and the screen going black with no explanation. `programs` is the number that
      // matters — it should be a small constant (one shared chunk material plus one per distinct
      // drop colour). If it climbs while you play, something is allocating materials per object.
      const info = gl.info
      onStats(`${cols.current.size} col · ${drawn.current.size} mesh · ${drops.current.length} drops · `
        + `geo ${info.memory.geometries} prog ${info.programs?.length ?? 0} · ${worker.current ? 'worker' : 'main'}`)
    }

    // ── evict ────────────────────────────────────────────────────────────────────────────────
    if (frame.current % 120 === 0) {
      const keep = new Set<string>()
      for (let dz = -RADIUS; dz <= RADIUS; dz++) for (let dx = -RADIUS; dx <= RADIUS; dx++) keep.add(key(cx + dx, cz + dz))
      for (const [mk, m] of drawn.current) {
        if (keep.has(mk.slice(0, mk.lastIndexOf(':')))) continue
        g.remove(m); m.geometry.dispose(); drawn.current.delete(mk)
      }
      for (const kk of [...cols.current.keys()]) if (!keep.has(kk)) cols.current.delete(kk)
      for (const kk of [...requested.current]) if (!keep.has(kk)) requested.current.delete(kk)
    }
  })

  return (
    <>
      <group ref={group} />
      <group ref={dropGroup} />
      {/* ⚠ Memoised. Inline `args={[new THREE.BoxGeometry(...)]}` builds a fresh geometry on EVERY
          React render and leaks the previous one — same family as the per-drop material that got
          the page's WebGL context blocked. */}
      <lineSegments ref={highlight} visible={false} geometry={highlightGeo}>
        <lineBasicMaterial color="#000000" transparent opacity={0.55} />
      </lineSegments>
    </>
  )
}
