'use client'

// The voxel world you can walk, mine and build in. A test bed, on its own route, on purpose.
//
// ⚠ NOT WIRED INTO Shimmer3D, DELIBERATELY. That file is ~5,900 lines of the live game (mortal
// side, holds, Crucible, and the warp/mount path that produced four bugs on 08-06) while this walks
// a DIFFERENT WORLD MODEL — no zones, no tiles, no warps. Integration is a later decision.
//
// ★ GENERATION RUNS IN A WORKER; MESHING AND EDITS STAY HERE. That split is deliberate. Mining
// edits a voxel and immediately re-meshes, so this thread has to own the Columns anyway — shipping
// one across the boundary per edit would cost more than it saves. The worker does the expensive,
// order-independent half (~109ms/chunk of noise, carving and ore) and hands back packed voxels;
// this thread wraps them into a Column and meshes (~47ms).
//
// ⚠ The worker URL is CONTENT-HASHED (`worker-url.ts`, generated by scripts/build-worker.mjs).
// It shipped as a fixed `/voxel-gen.worker.js` first, and /public caching pinned the browser to the
// FIRST build through every later deploy — a worker that answered old messages and ignored new ones,
// which reads exactly like a worker that half-works. Do not un-hash this.

import { useRef, useMemo, useState, useEffect, useCallback } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { PointerLockControls } from '@react-three/drei'
import * as THREE from 'three'
import { SECTION, DEFAULT_COLUMN, Column, Stage, makeColumn, meshColumn, refreshUniform } from '../voxel/column'
import { VOXEL_WORKER_URL } from '../../../workers/worker-url'
import { createMeshScratch } from '../voxel/greedy'
import { columnHeight } from '../voxel/height'
import { AIR } from '../voxel/section'
import { materialAt, MAT } from '../voxel/depth'
import { raycast, tickBreak, dropsFor, type BreakState } from '../voxel/mine'
import { spawnDrop, tickDrops, type Drop } from '../voxel/drops'
import { blockDef, materialForItem, type BlockSkill } from '../voxel/registry'
import { editIndex, recordEdit, applyEdits, packEdits, unpackEdits, isStale, type ColumnEdits } from '../voxel/edits'
import { loadColumn, saveColumn, editedColumnCount } from './save'
import { PIECES, STRUCTURE, pieceDef, cellsOf, canPlace, canAfford, placementAt, type Placement, type Rotation } from '../voxel/pieces'
import { createPieceRenderer } from './piece-mesh'
import { toGeometry, createVoxelMaterial, applySettings } from './mesh-bridge'
import { makeTileArray } from './tex/atlas'
import { createTexturedVoxelMaterial } from './tex/atlas'
import { loadSettings, saveSettings, withStyle, type VoxelSettings, type RenderStyle } from './settings'
import { buildAttrs, MATERIAL_COLOR } from './attrs'
import { createInventory, addItems, removeItems, countItem, type Inventory } from '../engine/inventory'
// ★ PORT STEP 1 — the zero-coupling systems, wired unchanged.
// PLAY3D-MIGRATION measured 16 of 23 engine systems as having NO reference to zones, tiles or world
// grids. These are three of them, imported exactly as `Shimmer3D` imports them: they do not know
// what the ground is made of, so moving the world out from under them costs nothing.
import { createSkillSet, addSkillXP, getMilestone, xpForSkillLevel, type SkillSet } from '../engine/skills'
import { ensureBasicTools, getEquippedTool, getToolDef, craftTool, canCraft as canCraftTool,
         TOOL_DEFS, type EquippedTools } from '../engine/tools'
// ── PORT STEP 2 — crafting, and it is NOT the engine/crafting.ts table ────────────────────────
// That table is a station catalogue (5 recipes, all "place a station"), it charges mana on
// everything, and it counts materials across a `BankState` the voxel world does not have. What a
// block world needs first is the layer the tile world never had: material → material. See the
// header of `voxel/recipes.ts` for why, including the bug it was already causing.
import { RECIPES, canCraft as canCraftRecipe, craftPlan, type RecipeDef } from '../voxel/recipes'
// ── PORT STEP 3 — the guns (2026-08-07, Alex ruled they cross into the Ather) ─────────────────
// `engine/weapons.ts` is the shared half: the table, the tuning, the pure ballistics. It was
// EXTRACTED from Shimmer3D rather than copied, because the thing that could not come across is
// collision — play3d's FiringRange resolves every hit against `gridRef.current[cz][cx]`, a tile
// grid this world does not have. So each walker owns its hit detection and shares the maths.
// Here that means voxel DDA (`raycast`, already used for mining), which is both simpler and more
// exact than what the tile version could do.
import { WEAPONS, weaponAt, ADS_FOV, spreadDeg, bloomAfterShot, bloomAfterRest,
         canFire, coneDirection, recoilKick, type WeaponDef } from '../engine/weapons'
// ── PORT STEP 4 — the clock (2026-08-07). `engine/day-cycle.ts` is pure wall-time maths, imported
// unchanged; the rig in day-night.tsx turns it into sky. This was the last shipped system reading
// as permanent noon: the light field's `dayFactor` finally has a day to factor.
import { VoxelDayNight } from './day-night'
import { dayProgress, getPhase, getDisplayTime, isTimePinned } from '../engine/day-cycle'

const SEED = 1337
const H = DEFAULT_COLUMN.worldHeight
const RADIUS = 6
const REACH = 6            // how far you can mine or place, in voxels
const key = (cx: number, cz: number) => `${cx},${cz}`

interface Slot { itemId: string; count: number }

/**
 * ★ THE HOTBAR CARRIES THE TOOLS (Alex, 2026-08-07): *"the hotbar uses the four tools as an
 * extension so the player can scroll over to the tool they need."*
 *
 * Slots 0-3 are the four gathering families in canon order, 4-7 are what you mined. The tools are
 * FIXED slots, not items — a tool is a thing you hold, not a stack you carry, and letting them
 * shuffle with inventory churn would move the spike out from under muscle memory mid-session.
 *
 * ⚠ FARMING IS THE FOURTH AND IT ONLY EXISTS AS OF TODAY. blades→forestry, spikes→prospecting,
 * rinsticks→rinning covered three; farming had no tool at all, which is why the spade was added
 * (engine/tools.ts). Four families, four slots — the row is not padded to look tidy.
 */
const TOOL_SLOTS = ['forestry', 'prospecting', 'rinning', 'farming'] as const
type ToolSkill = typeof TOOL_SLOTS[number]
type HotbarEntry =
  | { kind: 'tool'; skillId: ToolSkill; toolId: string | null; name: string; tier: number }
  | { kind: 'item'; itemId: string; count: number }
const ITEM_SLOT_0 = TOOL_SLOTS.length      // where the mined half of the row starts

export default function VoxelWorld() {
  const [stats, setStats] = useState('generating…')
  const [pos, setPos] = useState('')
  const [hotbar, setHotbar] = useState<HotbarEntry[]>([])
  // Stowed vs drawn. F toggles. See the DRAW LOCK note on the keydown handler.
  const [drawn, setDrawn] = useState(false)
  const [weaponIdx, setWeaponIdx] = useState(0)
  const [ammoUi, setAmmoUi] = useState(WEAPONS[0].clip)
  const [sel, setSel] = useState(0)
  const [tier, setTier] = useState(1)
  // ★ BUILD MODE. Blocks build the shell (mine/place, already there); pieces dress it. Tab switches
  // which verb the mouse means, so the two halves never fight over a click.
  const [build, setBuild] = useState(false)
  const [pieceIdx, setPieceIdx] = useState(0)
  const [rot, setRot] = useState<Rotation>(0)
  const [look, setLook] = useState<{ name: string; progress: number; refused: boolean } | null>(null)
  const [settings, setSettings] = useState<VoxelSettings>(() => loadSettings())
  const [showSettings, setShowSettings] = useState(false)
  const update = useCallback((patch: Partial<VoxelSettings>) => {
    setSettings(prev => { const next = { ...prev, ...patch }; saveSettings(next); return next })
  }, [])
  const worker = useRef<Worker | null>(null)
  const incoming = useRef<{ cx: number; cz: number; voxels: Uint16Array }[]>([])
  const inflight = useRef(0)

  useEffect(() => {
    let w: Worker
    try { w = new Worker(VOXEL_WORKER_URL) }
    catch (e) { setStats(`worker failed to start: ${String(e)} — main thread`); return }
    // Handler BEFORE post: assigning onmessage after postMessage races the first reply, and reads
    // as "the worker never answered".
    w.onmessage = (e) => {
      const m = e.data
      if (m.type === 'column') incoming.current.push({ cx: m.cx, cz: m.cz, voxels: m.voxels })
      else if (m.type === 'done') inflight.current = Math.max(0, inflight.current - 1)
    }
    w.onerror = (ev) => { setStats(`worker error: ${ev.message} — falling back to main thread`); worker.current = null }
    w.postMessage({ type: 'init', seed: SEED })
    worker.current = w
    return () => { w.terminate(); worker.current = null }
  }, [])

  // ★ THE SPIKE IS CANON, NOT INVENTED. `engine/tools.ts` rules blades→forestry,
  // spikes→prospecting, rinsticks→rinning, with a basic Greg-given tool that never breaks. So
  // "what do I mine rock with" already had an answer and nothing here needed naming.
  // Kept as refs so `World` reads them per-frame without re-rendering, but they are now DERIVED
  // from the equipped tool rather than set by a debug key.
  const toolTier = useRef(1)
  const toolSkill = useRef<BlockSkill>('prospecting')
  const inv = useRef<Inventory>(createInventory())
  // ★ Greg's basic tools, exactly as the tile game hands them out — `ensureBasicTools` fills any
  // missing skill with its never-breaking starter (worn_spike, worn_blade, worn_rinstick). The
  // debug tier lever is gone: tier now comes from what you are actually holding.
  const tools = useRef<EquippedTools>(ensureBasicTools({}))
  const skills = useRef<SkillSet>(createSkillSet())
  const [skillHud, setSkillHud] = useState<{ id: string; level: number; xp: number; next: number } | null>(null)
  const [levelUp, setLevelUp] = useState<string | null>(null)
  const [crafted, setCrafted] = useState<string | null>(null)
  // Owner status, for the legacy play3d door in the HUD only. ather.games has no cloud auth — it
  // comes from the httpOnly `ather_owner` cookie via /api/owner (set at /owner?key=OWNER_KEY).
  // Same pattern as Shimmer3D. It gates a LINK, not the route: /shimmer/play3d enforces its own
  // gate in proxy.ts, because a hidden link is not a permission.
  const [isOwner, setIsOwner] = useState(false)
  useEffect(() => {
    let alive = true
    fetch('/api/owner', { cache: 'no-store' })
      .then((r) => (r.ok ? r.json() : { owner: false }))
      .then((d) => { if (alive && d.owner) setIsOwner(true) })
      .catch(() => {})
    return () => { alive = false }
  }, [])
  // Toasts clear themselves. A level-up banner that never leaves stops being a level-up banner.
  useEffect(() => { if (!levelUp) return; const t = setTimeout(() => setLevelUp(null), 2600); return () => clearTimeout(t) }, [levelUp])
  useEffect(() => { if (!crafted) return; const t = setTimeout(() => setCrafted(null), 2600); return () => clearTimeout(t) }, [crafted])

  const refreshHotbar = useCallback(() => {
    const counts = new Map<string, number>()
    for (const s of inv.current.slots) if (s) counts.set(s.itemId, (counts.get(s.itemId) ?? 0) + s.count)
    const items: HotbarEntry[] = [...counts]
      .map(([itemId, count]) => ({ kind: 'item' as const, itemId, count }))
      .slice(0, 8 - ITEM_SLOT_0)
    const toolRow: HotbarEntry[] = TOOL_SLOTS.map((skillId) => {
      const held = getEquippedTool(tools.current!, skillId)
      const def = held ? getToolDef(held) : undefined
      // A family with nothing equipped still gets its slot, shown empty. Hiding it would renumber
      // the row the moment a tool broke, which is the same muscle-memory problem as reordering.
      return { kind: 'tool', skillId, toolId: held?.toolId ?? null, name: def?.name ?? '—', tier: def?.tier ?? 0 }
    })
    setHotbar([...toolRow, ...items])
  }, [])

  // ── The crafting surface ────────────────────────────────────────────────────────────────────
  // `craftTick` exists because the inventory is a REF, not state — crafting mutates it in place and
  // React has no way to know. Bumping a counter is what re-renders the panel with new counts. The
  // alternative (inventory in state) would re-render the whole world on every mined block.
  const [craftOpen, setCraftOpen] = useState(false)
  const [craftTick, setCraftTick] = useState(0)
  const have = useCallback((itemId: string) => countItem(inv.current!, itemId), [])

  /** Refine/build a recipe. The core hands back a plan; the host applies it. */
  const doCraft = useCallback((id: string) => {
    const plan = craftPlan(id)
    if (!plan || !canCraftRecipe(id, have)) return
    // Take everything BEFORE giving, and only give if every take succeeded — a partial spend that
    // still yields the output is a duplication bug, which is the one economy bug you cannot undo.
    if (!plan.take.every(t => countItem(inv.current!, t.itemId) >= t.count)) return
    for (const t of plan.take) removeItems(inv.current!, t.itemId, t.count)
    addItems(inv.current!, plan.give.itemId, plan.give.count)
    setCrafted(`${plan.give.count}× ${plan.give.itemId.replace(/_/g, ' ')}`)
    setCraftTick(t => t + 1)
    refreshHotbar()
  }, [have, refreshHotbar])

  /** Craft a tool and equip it. Tools keep their own table; this is the one surface that shows it. */
  const doCraftTool = useCallback((id: string) => {
    const def = TOOL_DEFS[id]
    if (!def || !canCraftTool(id, inv.current!)) return
    const made = craftTool(id, inv.current!)
    if (!made) return
    tools.current![def.skillId] = made
    setCrafted(def.name)
    setCraftTick(t => t + 1)
    refreshHotbar()
  }, [refreshHotbar])


  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const n = Number(e.key)
      // ── ★ THE DRAW LOCK (Alex, 2026-08-07) ────────────────────────────────────────────────
      // "when the player has a weapon stowed the hotbar kicks in and when they draw their weapon
      // the hotbar and tools lock up." F is the toggle, matching play3d's holster key so the two
      // walkers do not disagree about what F means.
      //
      // The lock is a MODE, not a disable: it blocks the verbs (mine, place, switch slot, build)
      // rather than hiding the row, so you can still see what you were holding and what you will
      // be holding again the moment you stow. A hotbar that vanished would make drawing feel like
      // losing your inventory.
      //
      // ⚠ The weapon itself is NOT here yet. Guns live inside Shimmer3D (a 3-entry WEAPONS table
      // plus the FiringRange rig) and porting them is its own step — this ships the mode and the
      // lock, which is the half that decides how the hotbar behaves. Alex ruled guns DO cross into
      // the Ather (2026-08-07), overturning the 07-22 aegis; that ruling still needs authoring into
      // world/lucernyx.md — see CANON_GAPS.md.
      if (e.code === 'KeyF') { setDrawn(d => !d); return }
      // Q swaps the model, and ONLY while drawn — with the weapon stowed Q would be a key that
      // silently changes something you cannot see, which is how a player learns not to trust a HUD.
      if (e.code === 'KeyQ' && drawn) { setWeaponIdx(i => { const n = (i + 1) % WEAPONS.length; setAmmoUi(WEAPONS[n].clip); return n }); return }
      if (drawn) return   // every verb below is locked while the weapon is out
      if (n >= 1 && n <= 8) { if (build) setPieceIdx(Math.min(PIECES.length - 1, n - 1)); else setSel(n - 1) }
      // Esc exits pointer lock anyway, so O is the settings key — it must not fight the browser.
      if (e.code === 'KeyO') setShowSettings(v => !v)
      if (e.code === 'Tab') { e.preventDefault(); setBuild(v => !v) }
      if (e.code === 'KeyR') setRot(r => ((r + 1) % 4) as Rotation)
      if (e.code === 'BracketLeft' || e.code === 'BracketRight') { /* spike tier, handled below */ }
      // Tool tier is a debug lever so the tier GATE can be felt in ten seconds: a tier-1 spike
      // REFUSES pure core, and that should be provable without crafting your way up first.
      // ★ THE TIER LEVER IS GONE. Tier comes from the equipped tool now, and a better tool is
      // CRAFTED from what you mined — which is the loop this port exists to close. C crafts the
      // next spike or blade you can afford.
      // C opens the crafting surface. It used to auto-craft the next affordable tool with no UI at
      // all, which hid the fact that the whole forestry ladder was uncraftable — you pressed C,
      // nothing happened, and nothing told you why. A list that shows what you CANNOT afford yet is
      // the difference between a broken key and a goal.
      if (e.code === 'KeyC') setCraftOpen(o => !o)
      if (e.code === 'Escape') setCraftOpen(false)
    }
    // Scroll to change slot — the reason tools are IN the row rather than on their own keys.
    const onWheel = (e: WheelEvent) => {
      if (build || drawn) return
      setSel(v => (v + (e.deltaY > 0 ? 1 : -1) + 8) % 8)
    }
    window.addEventListener('keydown', onKey)
    window.addEventListener('wheel', onWheel, { passive: true })
    return () => { window.removeEventListener('keydown', onKey); window.removeEventListener('wheel', onWheel) }
  }, [build, drawn])

  return (
    <div className="fixed inset-0 bg-[#0b0d14]">
      <Canvas camera={{ fov: 75, near: 0.1, far: 600 }} shadows={false}>
        {/* Sky, fog and all scene lights live in the rig now — the clock drives them. The old
            static five-liner IS the rig's DAY palette, so noon looks identical. */}
        <VoxelDayNight />
        <World
          inv={inv} toolTier={toolTier} toolSkill={toolSkill}
          /* A tool in hand is not a block in hand — RMB must not place while you hold a spade.
             `drawn` blanks it too: a weapon out means neither hand is free. */
          selItem={(() => { const e = hotbar[sel]; return !drawn && e?.kind === 'item' ? e.itemId : null })()}
          heldTool={(() => { const e = hotbar[sel]; return !drawn && e?.kind === 'tool' ? e.skillId : null })()}
          weaponDrawn={drawn}
          weaponIdx={weaponIdx}
          onAmmo={setAmmoUi}
          onStats={setStats} onPos={p => setPos(`x ${p.x.toFixed(0)}  y ${p.y.toFixed(0)}  z ${p.z.toFixed(0)}`)}
          onLook={setLook} onInvChange={refreshHotbar}
          worker={worker} incoming={incoming} inflight={inflight} settings={settings}
          build={build} pieceIdx={pieceIdx} rot={rot}
          tools={tools} skills={skills} onSkill={setSkillHud} onLevel={setLevelUp}
        />
        <PointerLockControls />
      </Canvas>
      <Hud stats={stats} pos={pos} look={look} hotbar={hotbar} sel={sel} tier={tier}
           build={build} pieceIdx={pieceIdx} rot={rot} inv={inv}
           skill={skillHud} levelUp={levelUp} crafted={crafted} tools={tools} isOwner={isOwner} drawn={drawn} weaponIdx={weaponIdx} ammoUi={ammoUi} />
      {showSettings && <SettingsPanel s={settings} update={update} onClose={() => setShowSettings(false)} />}
      {craftOpen && (
        <CraftPanel have={have} tools={tools} tick={craftTick}
                    onCraft={doCraft} onCraftTool={doCraftTool} onClose={() => setCraftOpen(false)} />
      )}
    </div>
  )
}

/**
 * The clock readout. Self-contained state on a 1s interval so the tick re-renders THIS chip and
 * nothing else — the sky reads the clock per-frame off in the Canvas; the HUD only needs minutes.
 * `PINNED` renders whenever `?hour=` froze the module clock, so a pinned art-pass tab can never be
 * mistaken for a broken cycle (the exact confusion the flag exists for — see day-cycle.ts).
 */
function Clock() {
  const [now, setNow] = useState(() => dayProgress())
  useEffect(() => {
    const t = setInterval(() => setNow(dayProgress()), 1000)
    return () => clearInterval(t)
  }, [])
  const phase = getPhase(now)
  const glyph = phase === 'night' ? '☾' : phase === 'day' ? '☀' : phase === 'dawn' ? '🌅' : '🌇'
  return (
    <div className="text-white/60 tabular-nums">
      {glyph} {getDisplayTime(now)} · {phase}
      {isTimePinned && <span className="ml-2 text-amber-300/90">PINNED</span>}
    </div>
  )
}

function Hud({ stats, pos, look, hotbar, sel, tier, build, pieceIdx, rot, inv, skill, levelUp, crafted, tools, isOwner, drawn, weaponIdx, ammoUi }: {
  stats: string; pos: string
  look: { name: string; progress: number; refused: boolean } | null
  hotbar: HotbarEntry[]; sel: number; tier: number
  build: boolean; pieceIdx: number; rot: Rotation
  inv: React.RefObject<Inventory>
  skill: { id: string; level: number; xp: number; next: number } | null
  levelUp: string | null
  crafted: string | null
  tools: React.RefObject<EquippedTools>
  isOwner: boolean
  drawn: boolean
  weaponIdx: number
  ammoUi: number
}) {
  return (
    <>
      <div className="absolute top-3 left-3 text-[11px] font-mono text-white/80 bg-black/45 rounded px-2.5 py-1.5 leading-relaxed pointer-events-none">
        {/* Not a test bed since 2026-08-07 — the room wall and /shimmer both land here now, so this
            is Shimmer. The label said TEST BED while it was reachable only by URL. */}
        <div className="text-white/95 font-semibold tracking-wide">SHIMMER</div>
        {/* A way OUT. This world had no exit and no entrance — you could only arrive by typing the
            URL and only leave with the back button. The parent block is pointer-events-none so the
            canvas keeps the mouse; these opt back in.
            The play3d link is the LEGACY door and is owner-only, the exact inverse of yesterday
            (play3d's ☰ menu held the owner-only door to here). play3d still holds the systems being
            ported across, so it stays reachable — just not to anyone who wandered in. */}
        <div className="flex gap-2 text-white/45 pointer-events-auto">
          <a href="/room?wall=0" className="hover:text-white/85 underline decoration-white/20">⌂ room</a>
          {isOwner && <a href="/shimmer/play3d" className="hover:text-white/85 underline decoration-white/20">❈ play3d (legacy)</a>}
        </div>
        <div>{pos}</div>
        <Clock />
        <div className="text-white/55">{stats}</div>
        <div className="mt-1 text-white/45">click to look · WASD · space · shift run · V fly</div>
        {build
          ? <div className="text-amber-200/80">BUILD · RMB place · LMB deconstruct · R rotate · 1-6 piece · Tab exit</div>
          : <div className="text-white/45">hold LMB mine · RMB place · scroll/1-8 slot · F draw · C craft · Tab build</div>}
        {/* ★ The tools are Greg's, from engine/tools.ts, unchanged. Tier is what you HOLD now. */}
        <div className="text-white/40 mt-1">
          {(['forestry', 'prospecting'] as const).map(sk => {
            const t = getEquippedTool(tools.current!, sk)
            const d = t ? getToolDef(t) : undefined
            return <span key={sk} className="mr-3">{sk.slice(0, 4)}: {d?.name ?? '—'}</span>
          })}
        </div>
      </div>

      {/* Skill progress — only while it is moving, so it is information rather than furniture. */}
      {skill && (
        <div className="absolute bottom-24 left-1/2 -translate-x-1/2 w-56 pointer-events-none">
          <div className="flex justify-between text-[10px] font-mono text-white/70 mb-0.5">
            <span className="uppercase tracking-wider">{skill.id}</span>
            <span className="tabular-nums">lv {skill.level}</span>
          </div>
          <div className="h-1 bg-black/55 rounded overflow-hidden">
            <div className="h-full bg-emerald-300" style={{ width: `${Math.min(100, (skill.xp / Math.max(1, skill.next)) * 100)}%` }} />
          </div>
        </div>
      )}

      {levelUp && (
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 text-center pointer-events-none">
          <div className="text-emerald-300 font-mono text-sm tracking-widest uppercase">{levelUp}</div>
        </div>
      )}
      {crafted && (
        <div className="absolute top-[38%] left-1/2 -translate-x-1/2 text-center pointer-events-none">
          <div className="text-amber-200 font-mono text-xs tracking-wider">crafted {crafted}</div>
        </div>
      )}
      <div className="hidden">
      </div>

      {look && (
        <div className="absolute left-1/2 top-[56%] -translate-x-1/2 text-center pointer-events-none">
          <div className={`text-[11px] font-mono tracking-wide ${look.refused ? 'text-red-300' : 'text-white/85'}`}>
            {look.name}{look.refused && ' — spike too weak'}
          </div>
          {look.progress > 0 && (
            <div className="mt-1 w-28 h-1 bg-black/50 rounded overflow-hidden mx-auto">
              <div className="h-full bg-amber-300" style={{ width: `${Math.min(100, look.progress * 100)}%` }} />
            </div>
          )}
        </div>
      )}

      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-1 h-1 rounded-full bg-white/80 pointer-events-none" />

      {/* ★ The build palette REPLACES the hotbar rather than sitting beside it. One bar, whose meaning
          follows the mode, so there is never a question about which row a number key is talking to. */}
      {build && (
        <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-1.5 pointer-events-none">
          {PIECES.map((pc, i) => {
            const affordable = pc.cost.every(c => countItem(inv.current!, c.itemId) >= c.count)
            return (
              <div key={pc.id} className={`w-20 h-14 rounded border-2 px-1 flex flex-col items-center justify-center text-[9px] font-mono
                ${i === pieceIdx ? 'border-amber-300 bg-black/70' : 'border-white/20 bg-black/45'}`}>
                <div className={i === pieceIdx ? 'text-amber-200' : 'text-white/70'}>{pc.name}</div>
                <div className={affordable ? 'text-white/45' : 'text-red-300/80'}>
                  {pc.cost.map(c => `${c.count}×${c.itemId.replace(/^block_|_plank$/g, '')}`).join(' ')}
                </div>
              </div>
            )
          })}
        </div>
      )}
      {build && (
        <div className="absolute bottom-[4.6rem] left-1/2 -translate-x-1/2 text-[10px] font-mono text-white/50 pointer-events-none">
          rotation {rot * 90}°
        </div>
      )}

      {/* Colour swatches stand in for item art — the registry maps materials to tiles.ts later.
          Slots 0-3 are the four tool families, 4-7 what you mined. The divider after slot 3 is the
          only thing telling the player the row has two halves, so it is not decoration.
          ★ DRAWN dims the whole row rather than hiding it: you keep seeing what you will be holding
          again when you stow, so drawing reads as "hands full", not "inventory gone". */}
      {!build && <div className={`absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-1.5 pointer-events-none transition-opacity ${drawn ? 'opacity-35' : 'opacity-100'}`}>
        {Array.from({ length: 8 }, (_, i) => {
          const e = hotbar[i]
          const isTool = e?.kind === 'tool'
          const mat = e?.kind === 'item' ? materialForItem(e.itemId) : undefined
          const swatch = mat !== undefined ? `#${(MATERIAL_COLOR[mat] ?? 0x888888).toString(16).padStart(6, '0')}` : undefined
          const selected = i === sel && !drawn
          return (
            <div key={i} className={`w-12 h-12 rounded border-2 flex flex-col items-center justify-center text-[9px] font-mono
              ${i === ITEM_SLOT_0 ? 'ml-3' : ''}
              ${selected ? 'border-amber-300 bg-black/60' : 'border-white/20 bg-black/40'}`}>
              {isTool ? (
                <>
                  {/* An unequipped family shows its slot greyed rather than empty — the row must not
                      renumber itself when a tool breaks. */}
                  <div className={`w-5 h-5 rounded-sm border ${e.toolId ? 'border-amber-200/50 bg-amber-200/15' : 'border-white/15 bg-white/5'}`} />
                  <div className={`mt-0.5 leading-none ${e.toolId ? 'text-white/70' : 'text-white/25'}`}>
                    {e.skillId.slice(0, 4)}{e.tier > 0 ? ` ${e.tier}` : ''}
                  </div>
                </>
              ) : e ? (
                <>
                  <div className="w-5 h-5 rounded-sm border border-white/25" style={{ background: swatch ?? '#6b7280' }} />
                  <div className="text-white/80 mt-0.5">{e.count}</div>
                </>
              ) : <span className="text-white/25">{i + 1}</span>}
            </div>
          )
        })}
      </div>}
      {/* The one piece of state the dimmed row cannot show by itself. */}
      {drawn && !build && (
        <div className="absolute bottom-[4.75rem] left-1/2 -translate-x-1/2 flex items-baseline gap-3 font-mono pointer-events-none">
          <span className="text-[11px] tracking-[.2em] uppercase text-amber-200/85">{WEAPONS[weaponIdx].name}</span>
          {/* tabular-nums so the count does not jitter the layout as it ticks down */}
          <span className="text-[13px] tabular-nums text-white/90">{ammoUi}<span className="text-white/35">/{WEAPONS[weaponIdx].clip}</span></span>
          <span className="text-[9px] tracking-[.18em] uppercase text-white/35">RMB aim · Q swap · F stow</span>
        </div>
      )}
      {!build && <div className="absolute bottom-[4.6rem] left-1/2 -translate-x-1/2 text-[10px] font-mono text-white/50 pointer-events-none">
        spike tier {tier}
      </div>}
    </>
  )
}

const SOLID_EXCEPT = new Set<number>([AIR, MAT.WATER])
const isSolid = (m: number) => !SOLID_EXCEPT.has(m)

function World({ inv, toolTier, toolSkill, selItem, heldTool, weaponDrawn, weaponIdx, onAmmo, onStats, onPos, onLook, onInvChange, worker, incoming, inflight, settings, build, pieceIdx, rot, tools, skills, onSkill, onLevel }: {
  inv: React.RefObject<Inventory>
  toolTier: React.RefObject<number>
  toolSkill: React.RefObject<BlockSkill>
  selItem: string | null
  /** The tool family the player has SELECTED, or null when holding a block/nothing. */
  heldTool: 'forestry' | 'prospecting' | 'rinning' | 'farming' | null
  /** Weapon out. Mining and placing are locked while true. Named `weaponDrawn`, not
   *  `drawn`: this component already has a `drawn` ref holding the rendered mesh map. */
  weaponDrawn: boolean
  /** Index into WEAPONS. Q cycles it; the parent owns it so the HUD can name the gun. */
  weaponIdx: number
  /** Rounds left, pushed up for the HUD. Called on fire and on reload completion. */
  onAmmo: (n: number) => void
  onStats: (s: string) => void
  onPos: (p: THREE.Vector3) => void
  onLook: (l: { name: string; progress: number; refused: boolean } | null) => void
  onInvChange: () => void
  worker: React.RefObject<Worker | null>
  incoming: React.RefObject<{ cx: number; cz: number; voxels: Uint16Array }[]>
  inflight: React.RefObject<number>
  settings: VoxelSettings
  build: boolean
  pieceIdx: number
  rot: Rotation
  tools: React.RefObject<EquippedTools>
  skills: React.RefObject<SkillSet>
  onSkill: (s: { id: string; level: number; xp: number; next: number } | null) => void
  onLevel: (s: string | null) => void
}) {
  const { camera } = useThree()
  const group = useRef<THREE.Group>(null)
  const highlight = useRef<THREE.LineSegments>(null)
  // ★ THE TEXTURE ARRAY, WIRED INTO THE MAIN WORLD (texture lane handoff, 406d492).
  //
  // One material for the whole world and ONE tile array — both keyed to `tileSize` so changing it
  // rebuilds exactly one texture rather than one per chunk. `sampler2DArray` is what makes this free
  // for the mesher: each material is its own LAYER, so RepeatWrapping tiles across a merged quad
  // with no bleed. An atlas cannot, and its usual escape (one quad per block) throws away the entire
  // greedy win — 67,629 quads would go back to 244,685.
  //
  // The flat vertex-colour material stays available and is NOT dead code: it is the control in the
  // A/B, and it is the fallback if tile generation ever throws.
  const { gl } = useThree()
  const tiles = useMemo(() => {
    try { return makeTileArray(settings.tileSize, gl) } catch { return null }
  }, [settings.tileSize, gl])
  const flatMaterial = useMemo(() => createVoxelMaterial(), [])
  const textured = useMemo(() => (tiles ? createTexturedVoxelMaterial(tiles) : null), [tiles])
  const material = textured?.material ?? flatMaterial

  // ★ A VALUE WRITE, NOT A REBUILD. Both shading paths live in the one compiled program and are
  // selected by a uniform, so changing style costs nothing and creates no second shader program.
  useEffect(() => {
    applySettings(flatMaterial, settings)
    textured?.setCartoon({
      uCartoon: settings.style === 'cartoon' ? 1 : 0,
      uToon: settings.toon,
      uOutline: settings.outline,
      uFaceShading: settings.faceShading,
      uShadowLift: settings.shadowLift,
    })
  }, [flatMaterial, textured, settings])
  const scratch = useMemo(() => createMeshScratch(SECTION), [])
  const cols = useRef(new Map<string, Column>())
  const drawn = useRef(new Map<string, THREE.Mesh>())
  const breaking = useRef<BreakState | null>(null)
  const drops = useRef<Drop[]>([])
  const dropMeshes = useRef(new Map<number, THREE.Mesh>())
  /**
   * ★ ONE GEOMETRY AND A MATERIAL CACHE FOR EVERY DROP — NOT ONE EACH.
   *
   * The first version built `new THREE.BoxGeometry` AND `new THREE.MeshLambertMaterial` per dropped
   * item. A material is a SHADER PROGRAM; a few hundred drops is a few hundred programs plus a few
   * hundred buffers, and Chrome responds by losing the WebGL context and then BLOCKING the page
   * from creating another one: "Web page caused context loss and was blocked", after which the
   * whole canvas is black and no amount of reloading helps until the tab is closed.
   *
   * This is the exact failure `mesh-bridge.ts` warns about for chunk meshes — "a material per chunk
   * is a shader program per chunk, and that is how a voxel renderer dies" — and I wrote that
   * warning and then did it anyway in the drop path. Geometry is shared outright; materials are
   * cached by colour, so the ceiling is the number of distinct block colours, not the number of
   * items on the floor.
   */
  const dropGeo = useMemo(() => new THREE.BoxGeometry(0.28, 0.28, 0.28), [])
  const dropMats = useRef(new Map<number, THREE.Material>())
  const highlightGeo = useMemo(() => new THREE.EdgesGeometry(new THREE.BoxGeometry(1.002, 1.002, 1.002)), [])
  const pieces = useMemo(() => createPieceRenderer(), [])
  // Placements are grouped by the column that OWNS them (the one containing the piece origin) —
  // the same ownership rule trees and carvers use, so a piece straddling a border saves once.
  const placements = useRef<Placement[]>([])
  const piecesByCol = useRef(new Map<string, Placement[]>())
  const colOf = useCallback((x: number, z: number) => key(Math.floor(x / SECTION), Math.floor(z / SECTION)), [])
  const dropGroup = useRef<THREE.Group>(null)
  const mouse = useRef({ left: false, right: false })
  // Weapon state. Refs, not state: these change per-frame and per-shot, and a re-render per round
  // fired would be a re-render of the whole world at 9 rounds/sec.
  const ammo = useRef(weaponAt(0).clip)
  const reloading = useRef(0)
  const ads = useRef(false)
  const recoil = useRef({ p: 0, y: 0 })
  const frame = useRef(0)
  const requested = useRef(new Set<string>())
  // ★ Edits live here, keyed by column, and are the ONLY thing the world stores. Walking a thousand
  // columns costs zero bytes; a save grows with what you BUILD.
  const edits = useRef(new Map<string, ColumnEdits>())
  const dirtySaves = useRef(new Set<string>())
  const staleWarned = useRef(false)
  const settled = useRef(false)
  const vel = useRef(new THREE.Vector3())
  // ★ Scratch vectors, allocated ONCE. Four `new THREE.Vector3()` per frame is 240 objects/sec of
  // pure garbage — not a GPU leak, but exactly the GC pressure the mesher and carver were both
  // rewritten to avoid. Same rule, applied to the frame loop instead of the hot inner loop.
  const vAim = useRef(new THREE.Vector3())
  const vFwd = useRef(new THREE.Vector3())
  const vRight = useRef(new THREE.Vector3())
  const vWish = useRef(new THREE.Vector3())
  const UP = useMemo(() => new THREE.Vector3(0, 1, 0), [])
  const keys = useRef<Record<string, boolean>>({})
  const fly = useRef(false)
  const onGround = useRef(false)

  useEffect(() => {
    // ⚠ FLY MOVED F → V (2026-08-07). F is now draw/stow, matching play3d's holster key so the two
    // walkers do not disagree about what F means — and draw/stow is a player verb while fly is a
    // debug convenience, so the player verb wins the good key. Caught only because the new binding
    // would have silently toggled BOTH: pressing F would have drawn your weapon and launched you.
    const kd = (e: KeyboardEvent) => { keys.current[e.code] = true; if (e.code === 'KeyV') fly.current = !fly.current }
    const ku = (e: KeyboardEvent) => { keys.current[e.code] = false }
    const md = (e: MouseEvent) => { if (e.button === 0) mouse.current.left = true; if (e.button === 2) mouse.current.right = true }
    const mu = (e: MouseEvent) => { if (e.button === 0) mouse.current.left = false; if (e.button === 2) mouse.current.right = false }
    const ctx = (e: Event) => e.preventDefault()
    window.addEventListener('keydown', kd); window.addEventListener('keyup', ku)
    window.addEventListener('mousedown', md); window.addEventListener('mouseup', mu)
    window.addEventListener('contextmenu', ctx)
    return () => {
      window.removeEventListener('keydown', kd); window.removeEventListener('keyup', ku)
      window.removeEventListener('mousedown', md); window.removeEventListener('mouseup', mu)
      window.removeEventListener('contextmenu', ctx)
    }
  }, [])

  useEffect(() => { camera.position.set(0.5, columnHeight(0, 0, SEED) + 2.6, 0.5) }, [camera])

  /** What is actually there. Unloaded reads as AIR — used for the raycast, so you can never target
   *  or mine a block that has not been generated. */
  // ★ EVERYTHING THIS COMPONENT ALLOCATES ON THE GPU IS RELEASED ON UNMOUNT. Without this, a
  // navigation away leaks every chunk geometry plus the shared material and drop resources — and a
  // page that leaks a full render's worth of buffers per visit is how the context gets lost in the
  // first place. The shared resources are disposed here and ONLY here, because disposing them
  // anywhere else would break every object still using them.
  /** Write every dirty column's blocks AND pieces in one record each. */
  const flushSaves = useCallback(() => {
    for (const k of dirtySaves.current) {
      const [gx, gz] = k.split(',').map(Number)
      const e = edits.current.get(k) ?? new Map()
      void saveColumn(SEED, gx, gz, { edits: packEdits(e), pieces: piecesByCol.current.get(k) ?? [] })
    }
    dirtySaves.current.clear()
  }, [])

  // ★ THE LAST SWING BEFORE A REFRESH MUST SURVIVE. A once-a-second flush loses up to a second of
  // building on a close, which is precisely the moment a player remembers.
  useEffect(() => {
    const flush = () => flushSaves()
    // `visibilitychange` rather than `beforeunload`: mobile and modern Chrome may never fire the
    // latter, and this is the event that is actually guaranteed before a tab goes away.
    document.addEventListener('visibilitychange', flush)
    window.addEventListener('pagehide', flush)
    return () => {
      flush()
      document.removeEventListener('visibilitychange', flush)
      window.removeEventListener('pagehide', flush)
    }
  }, [flushSaves])

  useEffect(() => () => {
    for (const m of drawn.current.values()) m.geometry.dispose()
    drawn.current.clear()
    dropMeshes.current.clear()
    for (const m of dropMats.current.values()) m.dispose()
    dropMats.current.clear()
    dropGeo.dispose()
    highlightGeo.dispose()
    pieces.dispose()
    flatMaterial.dispose()
    textured?.material.dispose()
    tiles?.texture.dispose()
  }, [dropGeo, highlightGeo, flatMaterial, textured, tiles, pieces])

  // ★ A LOST WEBGL CONTEXT MUST SAY SO. Chrome blocks a page that loses its context repeatedly, and
  // the result is a black canvas with the HUD still drawn on top — indistinguishable from a
  // generation failure, which is exactly why I hunted the mesher first when it happened. The block
  // is sticky for the life of the tab: reloading does not clear it, closing the tab does.
  useEffect(() => {
    const cv = gl.domElement
    const lost = (e: Event) => { e.preventDefault(); onStats('WEBGL CONTEXT LOST — close this tab and open a new one') }
    const restored = () => onStats('webgl context restored')
    cv.addEventListener('webglcontextlost', lost)
    cv.addEventListener('webglcontextrestored', restored)
    return () => { cv.removeEventListener('webglcontextlost', lost); cv.removeEventListener('webglcontextrestored', restored) }
  }, [gl, onStats])

  const voxel = useCallback((wx: number, wy: number, wz: number): number => {
    if (wy < 0 || wy >= H) return AIR
    const cx = Math.floor(wx / SECTION), cz = Math.floor(wz / SECTION)
    const c = cols.current.get(key(cx, cz))
    if (!c) return AIR
    return c.get(wx - cx * SECTION, wy, wz - cz * SECTION)
  }, [])

  /**
   * ★ COLLISION TREATS UNGENERATED SPACE AS SOLID, AND THAT IS THE WHOLE FIX FOR FALLING OFF THE
   * MAP. Sprinting is 22 units/s and generation is bounded, so a player outruns the load radius
   * routinely. With unloaded reading as AIR the floor simply is not there yet and you drop through
   * the world — which is what "I found a gap and fell off the map" actually was.
   *
   * Unknown terrain must BLOCK, never swallow. The worst case is standing still for a moment at the
   * edge of the world; the alternative is falling out of it. Note this deliberately differs from
   * `voxel` above: the raycast must NOT see phantom solids, or you would mine invisible blocks at
   * the frontier.
   */
  const voxelSolid = useCallback((wx: number, wy: number, wz: number): number => {
    if (wy < 0) return MAT.BEDROCK
    if (wy >= H) return AIR
    const cx = Math.floor(wx / SECTION), cz = Math.floor(wz / SECTION)
    const c = cols.current.get(key(cx, cz))
    if (!c) return MAT.BEDROCK          // not generated yet ⇒ stand on it, do not fall through it
    return c.get(wx - cx * SECTION, wy, wz - cz * SECTION)
  }, [])

  const remesh = useCallback((cx: number, cz: number) => {
    const g = group.current
    const c = cols.current.get(key(cx, cz))
    if (!g || !c) return
    const k = key(cx, cz)
    for (const [mk, m] of drawn.current) {
      if (!mk.startsWith(k + ':')) continue
      g.remove(m); m.geometry.dispose(); drawn.current.delete(mk)
    }
    for (const sm of meshColumn(c, {
      negX: cols.current.get(key(cx - 1, cz)) ?? null,
      posX: cols.current.get(key(cx + 1, cz)) ?? null,
      negZ: cols.current.get(key(cx, cz - 1)) ?? null,
      posZ: cols.current.get(key(cx, cz + 1)) ?? null,
    }, scratch)) {
      const mesh = new THREE.Mesh(toGeometry(buildAttrs(sm.mesh)), material)
      mesh.position.set(sm.wx, sm.wy, sm.wz)
      g.add(mesh)
      drawn.current.set(`${k}:${sm.index}`, mesh)
    }
  }, [material, scratch])

  /**
   * Write one voxel and repair the geometry.
   *
   * ★ THE NEIGHBOUR RE-MESH IS NOT OPTIONAL. Editing a voxel on a column's edge changes which faces
   * the NEIGHBOUR should draw — mine the last block of a column and, without this, the neighbour
   * keeps the wall it drew while that block still existed. It reads as an invisible pane you cannot
   * mine, sitting at exactly the seams a player walks along.
   *
   * `refreshUniform` matters for the same class of reason: the mesher's skip reads that table, and
   * a stale entry means dropped faces.
   */
  const setVoxel = useCallback((wx: number, wy: number, wz: number, mat: number) => {
    const cx = Math.floor(wx / SECTION), cz = Math.floor(wz / SECTION)
    const k = key(cx, cz)
    const c = cols.current.get(k)
    if (!c) return
    const lx = wx - cx * SECTION, lz = wz - cz * SECTION
    const s = (wy / SECTION) | 0

    // ★ Diff against what the GENERATOR would have put here, not against the current value — that
    // is what lets mining a block and putting it back return the save to empty instead of storing
    // a no-op forever. `materialAt` is pure, so the original is always recoverable without having
    // kept a pristine copy of the column around.
    const generated = materialAt(wx, wy, wz, SEED, c.heightAt(lx, lz))
    let e = edits.current.get(k)
    if (!e) { e = new Map(); edits.current.set(k, e) }
    recordEdit(e, editIndex(lx, wy, lz), mat, generated)
    dirtySaves.current.add(k)

    c.sections[s].set(lx, wy - s * SECTION, lz, mat)
    refreshUniform(c)
    remesh(cx, cz)
    if (lx === 0) remesh(cx - 1, cz)
    if (lx === SECTION - 1) remesh(cx + 1, cz)
    if (lz === 0) remesh(cx, cz - 1)
    if (lz === SECTION - 1) remesh(cx, cz + 1)
  }, [remesh])

  const blocked = useCallback((x: number, y: number, z: number) => {
    const y0 = Math.floor(y - 1.62), y1 = Math.floor(y - 1.62 + 1.75)
    for (let vy = y0; vy <= y1; vy++)
      for (const dx of [-0.3, 0.3]) for (const dz of [-0.3, 0.3])
        if (isSolid(voxelSolid(Math.floor(x + dx), vy, Math.floor(z + dz)))) return true
    return false
  }, [voxelSolid])

  // ── ★ THE FIRING RIG ─────────────────────────────────────────────────────────────────────────
  // Real travelling projectiles, not hitscan. The table already defines projSpeed/projLife per
  // model (a Lance round is a fast fat bolt, a Spitter round is not), and throwing that away for
  // hitscan would flatten the three feels the tuning exists to separate. It also matters the moment
  // mobs land: a projectile can be led and dodged, a hitscan cannot.
  //
  // ★ ONE SHARED MATERIAL FOR ALL TRACERS. A material per projectile is a shader program per
  // projectile, which is precisely what got this page BLOCKED from WebGL on 08-06 (black screen,
  // HUD alive, no console error) and why render-audit.test.ts exists. Full-auto would have hit that
  // within a second of holding the trigger.
  const shots = useRef<{ x: number; y: number; z: number; dx: number; dy: number; dz: number
                         speed: number; life: number; mesh: THREE.Mesh }[]>([])
  const tracerGeo = useMemo(() => new THREE.SphereGeometry(1, 6, 4), [])
  const tracerMat = useMemo(() => new THREE.MeshBasicMaterial({ color: 0xffd88a, toneMapped: false }), [])
  const impacts = useRef<{ mesh: THREE.Mesh; life: number }[]>([])
  const lastShot = useRef(0)
  const bloom = useRef(0)
  const semiLatch = useRef(false)   // semi-auto: one round per PRESS, not per frame held

  useEffect(() => () => {
    // Disposed together — the geometry and material are shared, so a leak here leaks once, but a
    // route change that leaves them alive leaks a GPU buffer per visit.
    tracerGeo.dispose(); tracerMat.dispose()
  }, [tracerGeo, tracerMat])

  // Swapping models refills to that model's clip. Carrying rounds across a swap would let a
  // Repeater's 12 become a Lance's 12 against a clip of 8, and the HUD would disagree with the sim.
  useEffect(() => {
    ammo.current = weaponAt(weaponIdx).clip
    reloading.current = 0
    bloom.current = 0
    onAmmo(ammo.current)
  }, [weaponIdx, onAmmo])

  const fire = useCallback((w: WeaponDef, g: THREE.Group) => {
    const f = new THREE.Vector3()
    camera.getWorldDirection(f)
    const [dx, dy, dz] = coneDirection(f.x, f.y, f.z, spreadDeg(w, bloom.current, ads.current), Math.random(), Math.random())
    const mesh = new THREE.Mesh(tracerGeo, tracerMat)
    mesh.scale.setScalar(w.headR)
    // Spawned at the camera, not at a muzzle offset: this world has no viewmodel yet, and a
    // convergence fudge with nothing to converge FROM would just put rounds where the eye is not.
    mesh.position.copy(camera.position)
    g.add(mesh)
    shots.current.push({ x: camera.position.x, y: camera.position.y, z: camera.position.z,
                         dx, dy, dz, speed: w.projSpeed, life: w.projLife, mesh })
    ammo.current = Math.max(0, ammo.current - 1)
    bloom.current = bloomAfterShot(w, bloom.current)
    const kick = recoilKick(w, Math.random)
    recoil.current.p += kick.pitch; recoil.current.y += kick.yaw
    lastShot.current = 0
    onAmmo(ammo.current)
  }, [camera, tracerGeo, tracerMat, onAmmo])

  useFrame((_, dtRaw) => {
    const dt = Math.min(dtRaw, 0.05)
    const g = group.current
    if (!g) return
    const p = camera.position
    const cx = Math.floor(p.x / SECTION), cz = Math.floor(p.z / SECTION)

    // ── ★ WEAPON TICK ────────────────────────────────────────────────────────────────────────
    // Runs before the mine/place block below, and that block is already gated on !weaponDrawn — so
    // the two verbs can never both consume the same click. That is the whole draw lock in one line.
    {
      const w = weaponAt(weaponIdx)
      lastShot.current += dt
      ads.current = weaponDrawn && mouse.current.right
      // ADS zoom is lerped, never snapped: an instant FOV change reads as a teleport.
      const wantFov = ads.current ? ADS_FOV : 75
      const cam = camera as THREE.PerspectiveCamera
      if (Math.abs(cam.fov - wantFov) > 0.01) { cam.fov += (wantFov - cam.fov) * Math.min(1, dt * 12); cam.updateProjectionMatrix() }

      if (reloading.current > 0) {
        reloading.current -= dt
        if (reloading.current <= 0) { ammo.current = w.clip; onAmmo(ammo.current) }
      }
      if (!weaponDrawn) { bloom.current = bloomAfterRest(w, bloom.current, dt); semiLatch.current = false }
      else {
        if (mouse.current.left) {
          // Full-auto keeps firing while held; semi-auto needs the button to come back up first.
          const mayPress = w.auto || !semiLatch.current
          if (mayPress && canFire(w, lastShot.current, ammo.current, reloading.current)) { fire(w, g); semiLatch.current = true }
          else if (ammo.current <= 0 && reloading.current <= 0) reloading.current = w.reloadTime
        } else {
          semiLatch.current = false
          bloom.current = bloomAfterRest(w, bloom.current, dt)
        }
      }

      // Recoil is DRAINED into the camera here rather than written at fire time, so a burst climbs
      // smoothly instead of snapping once per round.
      if (recoil.current.p !== 0 || recoil.current.y !== 0) {
        camera.rotation.x += recoil.current.p * Math.min(1, dt * 18)
        camera.rotation.y += recoil.current.y * Math.min(1, dt * 18)
        const k = 1 - Math.min(1, dt * 18)
        recoil.current.p *= k; recoil.current.y *= k
      }

      // ── projectiles ────────────────────────────────────────────────────────────────────────
      // Each round raycasts the SEGMENT it travelled this frame, never just its endpoint. At 54
      // units/sec a Lance round covers ~0.9 units per frame, so endpoint sampling would tunnel
      // straight through any wall thinner than that — the classic fast-projectile bug.
      for (let i = shots.current.length - 1; i >= 0; i--) {
        const sh = shots.current[i]
        const step = sh.speed * dt
        const hit = raycast(sh.x, sh.y, sh.z, sh.dx, sh.dy, sh.dz, step, voxelSolid)
        sh.life -= dt
        if (hit) {
          // Impact marker at the face, small and short-lived — the read is "I hit that block".
          const m = new THREE.Mesh(tracerGeo, tracerMat)
          m.scale.setScalar(0.12)
          m.position.set(hit.x + 0.5, hit.y + 0.5, hit.z + 0.5)
          g.add(m); impacts.current.push({ mesh: m, life: 0.25 })
          g.remove(sh.mesh); shots.current.splice(i, 1)
          continue
        }
        sh.x += sh.dx * step; sh.y += sh.dy * step; sh.z += sh.dz * step
        sh.mesh.position.set(sh.x, sh.y, sh.z)
        if (sh.life <= 0) { g.remove(sh.mesh); shots.current.splice(i, 1) }
      }
      for (let i = impacts.current.length - 1; i >= 0; i--) {
        const im = impacts.current[i]
        im.life -= dt
        im.mesh.scale.setScalar(0.12 * Math.max(0, im.life / 0.25))
        if (im.life <= 0) { g.remove(im.mesh); impacts.current.splice(i, 1) }
      }
    }

    // ── adopt whatever the worker finished ───────────────────────────────────────────────────
    // Wrapping packed voxels into a Column is a view, not a copy: the sections point straight into
    // the transferred buffer, so adopting a generated column costs nothing.
    const t0 = performance.now()
    let adopted = 0
    while (incoming.current!.length && adopted < 2) {
      const { cx: gx, cz: gz, voxels } = incoming.current!.shift()!
      const col = new Column(gx * SECTION, gz * SECTION)
      const per = SECTION * SECTION * SECTION
      for (let i = 0; i < col.sections.length; i++) col.sections[i].data.set(voxels.subarray(i * per, (i + 1) * per))
      for (let z = 0; z < SECTION; z++) for (let x = 0; x < SECTION; x++)
        col.surface[z * SECTION + x] = columnHeight(gx * SECTION + x, gz * SECTION + z, SEED)
      // ★ Apply any stored edits OVER freshly generated terrain — the diff is the save.
      // Edits arrive asynchronously from IndexedDB, so a column may mesh once procedurally and then
      // again once its edits land. That is deliberate: blocking the world on a database read would
      // stall streaming for the common case, which is a column with no edits at all.
      const ek = key(gx, gz)
      applyEdits(col, edits.current.get(ek))
      refreshUniform(col)
      col.stage = Stage.Ready
      cols.current.set(ek, col)
      remesh(gx, gz)
      if (!edits.current.has(ek)) {
        loadColumn(SEED, gx, gz).then(saved => {
          if (!saved) { edits.current.set(ek, new Map()); return }
          if (isStale(saved.edits) && !staleWarned.current) {
            staleWarned.current = true
            onStats('⚠ saved edits are from a different generator version — they may not line up')
          }
          const m = unpackEdits(saved.edits)
          edits.current.set(ek, m)
          const c = cols.current.get(ek)
          if (c && m.size) { applyEdits(c, m); refreshUniform(c); remesh(gx, gz) }
          // Pieces come back with their blocks. Occupancy is NOT re-written here — it is already in
          // the block diff, because placing a piece wrote STRUCTURE through `setVoxel`, which is a
          // recorded edit. Writing it twice would be harmless but would double the save.
          if (saved.pieces?.length) {
            piecesByCol.current.set(ek, saved.pieces)
            placements.current = [...placements.current, ...saved.pieces]
            pieces.sync(placements.current)
          }
        })
      }
      for (const [ddx, ddz] of [[-1, 0], [1, 0], [0, -1], [0, 1]] as const)
        if (cols.current.has(key(gx + ddx, gz + ddz))) remesh(gx + ddx, gz + ddz)
      adopted++
    }

    // ── request what is missing, nearest first ───────────────────────────────────────────────
    const want: [number, number, number][] = []
    for (let dz = -RADIUS; dz <= RADIUS; dz++) for (let dx = -RADIUS; dx <= RADIUS; dx++) {
      const d = dx * dx + dz * dz
      if (d > RADIUS * RADIUS) continue
      const kk = key(cx + dx, cz + dz)
      if (!cols.current.has(kk) && !requested.current.has(kk)) want.push([d, cx + dx, cz + dz])
    }
    want.sort((a, b) => a[0] - b[0])
    const w = worker.current
    for (const [, gx, gz] of want) {
      if (w) {
        if (inflight.current! >= 4) break
        requested.current.add(key(gx, gz))
        inflight.current!++
        w.postMessage({ type: 'request', cx: gx, cz: gz })
      } else {
        // No worker (construction failed): generate here so the world still exists.
        if (performance.now() - t0 > 10) break
        requested.current.add(key(gx, gz))
        cols.current.set(key(gx, gz), makeColumn(gx * SECTION, gz * SECTION, SEED))
        remesh(gx, gz)
        for (const [ddx, ddz] of [[-1, 0], [1, 0], [0, -1], [0, 1]] as const)
          if (cols.current.has(key(gx + ddx, gz + ddz))) remesh(gx + ddx, gz + ddz)
      }
    }

    // Until the spawn column exists every lookup returns AIR, so gravity would drop the player
    // through a world that has not generated yet. Hold until there is ground beneath.
    if (!settled.current) {
      if (isSolid(voxel(0, Math.floor(p.y) - 3, 0))) settled.current = true   // real ground, not the phantom floor
      else { onPos(p); onStats(`${cols.current.size} columns · generating…`); return }
    }

    // ── movement ─────────────────────────────────────────────────────────────────────────────
    const k = keys.current
    const speed = (k.ShiftLeft ? 22 : 9) * (fly.current ? 2.2 : 1)
    const aim = vAim.current
    camera.getWorldDirection(aim)
    const fwd = vFwd.current.copy(aim); fwd.y = 0; fwd.normalize()
    const right = vRight.current.crossVectors(fwd, UP)
    const wish = vWish.current.set(0, 0, 0)
    if (k.KeyW) wish.add(fwd)
    if (k.KeyS) wish.sub(fwd)
    if (k.KeyD) wish.add(right)
    if (k.KeyA) wish.sub(right)
    if (wish.lengthSq() > 0) wish.normalize().multiplyScalar(speed)

    if (fly.current) {
      if (k.Space) wish.y += speed
      if (k.ControlLeft) wish.y -= speed
      p.addScaledVector(wish, dt)
    } else {
      vel.current.x = wish.x; vel.current.z = wish.z
      vel.current.y -= 28 * dt
      if (onGround.current && k.Space) vel.current.y = 9.2
      const nx = p.x + vel.current.x * dt
      if (!blocked(nx, p.y, p.z)) p.x = nx
      const nz = p.z + vel.current.z * dt
      if (!blocked(p.x, p.y, nz)) p.z = nz
      const ny = p.y + vel.current.y * dt
      if (!blocked(p.x, ny, p.z)) { p.y = ny; onGround.current = false }
      else { if (vel.current.y < 0) onGround.current = true; vel.current.y = 0 }
      if (p.y < -20) { p.set(0.5, columnHeight(0, 0, SEED) + 2.6, 0.5); settled.current = false }
    }

    // ── what are we looking at ───────────────────────────────────────────────────────────────
    const hit = raycast(p.x, p.y, p.z, aim.x, aim.y, aim.z, REACH, voxel)
    const hl = highlight.current
    if (hl) {
      hl.visible = !!hit
      if (hit) hl.position.set(hit.x + 0.5, hit.y + 0.5, hit.z + 0.5)
    }

    // ── build mode: ghost, place, deconstruct ────────────────────────────────────────────────
    if (build) {
      const def = pieceDef(PIECES[pieceIdx].id)!
      // The ghost sits in the EMPTY cell before what you are looking at — the same `px,py,pz` that
      // block placement uses, so both verbs agree about where "in front of" is.
      const target: Placement | null = hit ? { pieceId: def.id, x: hit.px, y: hit.py, z: hit.pz, rot } : null
      const fits = !!target && canPlace(target, def, (x, y, z) => voxel(x, y, z))
      const afford = canAfford(def, id => countItem(inv.current!, id))
      if (target) pieces.setGhost(def.id, target.x, target.y, target.z, rot, fits && afford)
      else pieces.hideGhost()

      if (target && mouse.current.right && fits && afford) {
        for (const c of def.cost) removeItems(inv.current!, c.itemId, c.count)
        // ★ OCCUPANCY INTO THE VOXEL GRID — this is what makes collision free. Only the SOLID cells
        // are written, so a doorway stays walkable and a stair can be climbed.
        for (const c of cellsOf(target, def)) if (c.solid) setVoxel(c.x, c.y, c.z, STRUCTURE)
        placements.current.push(target)
        const ok = colOf(target.x, target.z)
        piecesByCol.current.set(ok, [...(piecesByCol.current.get(ok) ?? []), target])
        dirtySaves.current.add(ok)
        pieces.sync(placements.current)
        onInvChange()
        mouse.current.right = false
      }

      // Deconstruct: aim at ANY cell the piece occupies, not just its origin.
      if (hit && mouse.current.left) {
        const found = placementAt(placements.current, hit.x, hit.y, hit.z)
        if (found) {
          const fdef = pieceDef(found.pieceId)!
          for (const c of cellsOf(found, fdef)) if (c.solid) setVoxel(c.x, c.y, c.z, AIR)
          // Full refund while the loop is unproven — consequence-free experimenting is what you want
          // while judging feel. A dial, not a ruling.
          for (const c of fdef.cost) addItems(inv.current!, c.itemId, c.count)
          placements.current = placements.current.filter(p => p !== found)
          const fk = colOf(found.x, found.z)
          piecesByCol.current.set(fk, (piecesByCol.current.get(fk) ?? []).filter(p => p !== found))
          dirtySaves.current.add(fk)
          pieces.sync(placements.current)
          onInvChange()
          mouse.current.left = false
        }
      }

      onLook(hit ? { name: `${def.name}${!afford ? ' — need materials' : fits ? '' : ' — blocked'}`, progress: 0, refused: !fits || !afford } : null)
      onPos(p)
      if (++frame.current % 10 === 0) {
        const info = gl.info
        onStats(`${cols.current.size} col · ${placements.current.length} pieces · geo ${info.memory.geometries} prog ${info.programs?.length ?? 0} · BUILD`)
      }
      return
    }
    pieces.hideGhost()

    // ── mine ─────────────────────────────────────────────────────────────────────────────────
    // ★ THE TOOL IS CHOSEN BY THE BLOCK, NOT BY A HOTKEY. Every block declares its skill, and the
    // matching equipped tool supplies the tier and speed — so a spike cuts rock and a blade cuts
    // wood without the player switching anything. That is the tile game's model, unchanged; it just
    // never had a world where both mattered on the same swing.
    if (hit && mouse.current.left && !weaponDrawn) {
      const hitDef = blockDef(hit.material)
      // ★ THE HELD TOOL WINS, AND AUTO-PICK IS THE FALLBACK (changed 2026-08-07).
      // This used to be pure auto-pick — the block chose the tool and the player never switched.
      // Alex wants the tool in hand to be a thing you choose, so a selected tool is now used as-is:
      // hold the spade on dirt and you dig fast, hold it on stone and stone refuses you, which is
      // what makes choosing mean anything.
      //
      // But a player holding a BLOCK (or an empty slot) must not be unable to mine — that would
      // make the row a trap rather than a choice. In that case the old behaviour stands and the
      // block picks its own tool. So: choosing is meaningful, forgetting is survivable.
      const wantSkill: BlockSkill = (heldTool as BlockSkill | null) ?? hitDef?.skill ?? null
      const equipped = wantSkill ? getEquippedTool(tools.current!, wantSkill as never) : undefined
      const eDef = equipped ? getToolDef(equipped) : undefined
      toolSkill.current = wantSkill
      toolTier.current = eDef?.tier ?? 0
      const r = tickBreak(breaking.current, hit, dt, toolTier.current!, toolSkill.current!, eDef?.speedBonus ?? 1)
      breaking.current = r.state
      if (r.broken) {
        // ★ XP GOES TO THE BLOCK'S SKILL. Mining ore trains Prospecting, felling a tree trains
        // Forestry — the two halves of gathering finally exist in the same world, which is the whole
        // reason this port was worth doing before combat or NPCs.
        if (wantSkill && skills.current![wantSkill as keyof SkillSet]) {
          const sk = skills.current![wantSkill as keyof SkillSet]
          // XP scales with hardness, so the deep tiers train faster than topsoil — the ladder the
          // registry already encodes, reused rather than restated.
          const res = addSkillXP(sk, Math.max(4, Math.round((hitDef?.hardness ?? 1) * 12)))
          if (res.leveled) {
            onLevel(`${wantSkill} ${res.newLevel}${getMilestone(res.newLevel) ? ' — ' + getMilestone(res.newLevel) : ''}`)
          }
          onSkill({ id: wantSkill, level: sk.level, xp: sk.xp, next: xpForSkillLevel(sk.level) })
        }
        // ★ The block bursts into an ENTITY on the floor, it does not teleport into the satchel.
        // Straight-to-inventory works and feels like nothing happened; seeing the shard fall is
        // what tells the player the swing landed and what the vein actually yielded.
        for (const d of dropsFor(hit.material)) drops.current.push(spawnDrop(d.itemId, d.count, hit.x, hit.y, hit.z))
        setVoxel(hit.x, hit.y, hit.z, AIR)
        breaking.current = null
      }
    } else if (!mouse.current.left) {
      breaking.current = null
    }

    // ── place ────────────────────────────────────────────────────────────────────────────────
    if (hit && mouse.current.right && selItem && !weaponDrawn) {
      const mat = materialForItem(selItem)
      // Refuse to place inside your own body — the classic way to entomb yourself.
      const inPlayer = Math.floor(p.x) === hit.px && Math.floor(p.z) === hit.pz
        && (Math.floor(p.y) === hit.py || Math.floor(p.y - 1.62) === hit.py)
      if (mat !== undefined && !inPlayer && countItem(inv.current!, selItem) > 0 && voxel(hit.px, hit.py, hit.pz) === AIR) {
        removeItems(inv.current!, selItem, 1)
        setVoxel(hit.px, hit.py, hit.pz, mat)
        onInvChange()
        mouse.current.right = false   // one block per click, not a firehose
      }
    }

    // ── dropped items ────────────────────────────────────────────────────────────────────────
    // Physics resolves against the voxel grid (not a heightfield), so a shard mined in a cave rests
    // on the cave floor rather than on the surface hundreds of blocks above it.
    if (drops.current.length) {
      const res = tickDrops(drops.current, dt, p.x, p.y - 0.8, p.z,
        (x, y, z) => isSolid(voxelSolid(x, y, z)))
      if (res.picked.length) {
        for (const it of res.picked) addItems(inv.current!, it.itemId, it.count)
        onInvChange()
      }
    }
    const dg = dropGroup.current
    if (dg) {
      const live = new Set<number>()
      for (const d of drops.current) {
        live.add(d.id)
        let m = dropMeshes.current.get(d.id)
        if (!m) {
          const mat = materialForItem(d.itemId)
          const colour = mat !== undefined ? (MATERIAL_COLOR[mat] ?? 0xcccccc) : 0xffd479
          let dm = dropMats.current.get(colour)
          if (!dm) {
            dm = new THREE.MeshLambertMaterial({ color: colour, emissive: colour, emissiveIntensity: 0.25 })
            dropMats.current.set(colour, dm)
          }
          m = new THREE.Mesh(dropGeo, dm)
          dg.add(m)
          dropMeshes.current.set(d.id, m)
        }
        // Bob and spin so a shard on a grey cave floor is findable rather than camouflaged.
        m.position.set(d.x, d.y + (d.resting ? 0.06 * Math.sin(d.age * 3) : 0), d.z)
        m.rotation.y = d.age * 1.6
      }
      for (const [id, m] of dropMeshes.current) {
        if (live.has(id)) continue
        // Geometry and material are SHARED — disposing them here would destroy every other drop's
        // rendering. Only the Mesh wrapper is thrown away.
        dg.remove(m)
        dropMeshes.current.delete(id)
      }
    }

    // ── HUD ──────────────────────────────────────────────────────────────────────────────────
    const def = hit ? blockDef(hit.material) : undefined
    onLook(hit && def
      ? {
          name: def.name,
          progress: breaking.current ? breaking.current.progress / breaking.current.required : 0,
          refused: mouse.current.left && !breaking.current && def.hardness !== Infinity,
        }
      : null)
    onPos(p)
    if (++frame.current % 10 === 0) {
      // ★ GPU RESOURCE COUNTS IN THE HUD. A leak used to announce itself by Chrome blocking the
      // context and the screen going black with no explanation. `programs` is the number that
      // matters — it should be a small constant (one shared chunk material plus one per distinct
      // drop colour). If it climbs while you play, something is allocating materials per object.
      const info = gl.info
      let built = 0
      for (const e of edits.current.values()) built += e.size
      onStats(`${cols.current.size} col · ${drawn.current.size} mesh · ${drops.current.length} drops · `
        + `geo ${info.memory.geometries} prog ${info.programs?.length ?? 0} · `
        + `${built} edits saved · ${worker.current ? 'worker' : 'main'}`)
    }

    // ── flush edits ──────────────────────────────────────────────────────────────────────────
    // ★ Debounced, not per-block. Mining is a stream of edits and an IndexedDB write per broken
    // block would put a transaction on every swing. Once a second is imperceptible to a player and
    // invisible to the frame budget.
    if (frame.current % 60 === 0 && dirtySaves.current.size) {
      flushSaves()
    }

    // ── evict ────────────────────────────────────────────────────────────────────────────────
    if (frame.current % 120 === 0) {
      const keep = new Set<string>()
      for (let dz = -RADIUS; dz <= RADIUS; dz++) for (let dx = -RADIUS; dx <= RADIUS; dx++) keep.add(key(cx + dx, cz + dz))
      for (const [mk, m] of drawn.current) {
        if (keep.has(mk.slice(0, mk.lastIndexOf(':')))) continue
        g.remove(m); m.geometry.dispose(); drawn.current.delete(mk)
      }
      for (const kk of [...cols.current.keys()]) if (!keep.has(kk)) cols.current.delete(kk)
      for (const kk of [...requested.current]) if (!keep.has(kk)) requested.current.delete(kk)
      // ⚠ EDITS ARE NOT EVICTED WITH THEIR COLUMN. Walking away from a house and back must not lose
      // it — the column is regenerable, the edits are not. Any still-unsaved ones are flushed first,
      // because dropping the column while its diff sits in `dirtySaves` is exactly how a build
      // vanishes on a walk.
      flushSaves()
    }
  })

  return (
    <>
      <group ref={group} />
      <group ref={dropGroup} />
      <primitive object={pieces.group} />
      {/* ⚠ Memoised. Inline `args={[new THREE.BoxGeometry(...)]}` builds a fresh geometry on EVERY
          React render and leaks the previous one — same family as the per-drop material that got
          the page's WebGL context blocked. */}
      <lineSegments ref={highlight} visible={false} geometry={highlightGeo}>
        <lineBasicMaterial color="#000000" transparent opacity={0.55} />
      </lineSegments>
    </>
  )
}

/**
 * The crafting surface (C).
 *
 * ★ IT LISTS WHAT YOU CANNOT AFFORD, AND THAT IS THE POINT. C used to silently auto-craft the best
 * tool you could pay for, which is why nobody noticed the entire forestry ladder was uncraftable:
 * you pressed a key, nothing happened, and the game never said whether that meant "no materials",
 * "already have it", or "this is impossible". A greyed row with its costs showing turns a dead key
 * into a goal.
 *
 * Two sections, one surface. Refining comes from the pure-core table (`voxel/recipes.ts`); tools
 * keep their own canon table (`engine/tools.ts`, blades→forestry / spikes→prospecting) and are
 * shown here rather than given a second window.
 *
 * `tick` is the re-render handle: the inventory is a ref that crafting mutates in place, so this
 * panel has no other way to know its counts changed.
 */
function CraftPanel({ have, tools, tick, onCraft, onCraftTool, onClose }: {
  have: (itemId: string) => number
  tools: React.RefObject<EquippedTools>
  tick: number
  onCraft: (id: string) => void
  onCraftTool: (id: string) => void
  onClose: () => void
}) {
  const label = (id: string) => id.replace(/_/g, ' ')
  const Cost = ({ items }: { items: { itemId: string; count: number }[] }) => (
    <span className="text-white/45">
      {items.map((c, i) => (
        <span key={c.itemId} className={have(c.itemId) >= c.count ? 'text-emerald-300/70' : 'text-rose-300/60'}>
          {i > 0 && <span className="text-white/25"> · </span>}
          {label(c.itemId)} {have(c.itemId)}/{c.count}
        </span>
      ))}
    </span>
  )

  // The next unearned tier per skill. Showing all nine at once buries the one you are working
  // toward; showing only what you can afford is what hid the bug in the first place.
  const nextTools = (['forestry', 'prospecting'] as const).flatMap((skillId) => {
    const held = getEquippedTool(tools.current!, skillId)
    const heldTier = held ? (getToolDef(held)?.tier ?? 0) : 0
    const next = Object.values(TOOL_DEFS)
      .filter(d => !d.basic && d.skillId === skillId && d.tier > heldTier)
      .sort((a, b) => a.tier - b.tier)[0]
    return next ? [next] : []
  })

  const rows = RECIPES.filter(r => r.input.every(i => have(i.itemId) > 0 || canCraftRecipe(r.id, have)))

  return (
    <div className="absolute inset-0 grid place-items-center bg-black/50 pointer-events-auto" onClick={onClose}>
      <div className="w-[440px] max-h-[80vh] overflow-y-auto bg-[#0e1018]/95 border border-white/12 rounded-lg p-4 font-mono text-[11px]"
           onClick={(e) => e.stopPropagation()}>
        <div className="flex items-baseline justify-between mb-3">
          <span className="text-white/95 font-semibold tracking-[.18em] uppercase">Crafting</span>
          <button onClick={onClose} className="text-white/40 hover:text-white/80">esc</button>
        </div>

        <div className="text-white/40 tracking-[.14em] uppercase text-[9px] mb-1.5">Refine</div>
        {rows.length === 0 && <div className="text-white/35 mb-3">nothing to refine — go cut a tree</div>}
        {rows.map((r: RecipeDef) => {
          const can = canCraftRecipe(r.id, have)
          return (
            <button key={r.id} disabled={!can} onClick={() => onCraft(r.id)}
                    className={`w-full text-left mb-1 px-2 py-1.5 rounded border transition-colors ${
                      can ? 'border-white/15 hover:border-amber-200/50 hover:bg-white/5 text-white/90'
                          : 'border-white/5 text-white/30 cursor-not-allowed'}`}>
              <div className="flex justify-between gap-3">
                <span>{r.name}</span>
                <span className="text-amber-200/70 tabular-nums">{r.output.count}× {label(r.output.itemId)}</span>
              </div>
              <div className="mt-0.5 text-[10px]"><Cost items={r.input} /></div>
            </button>
          )
        })}

        <div className="text-white/40 tracking-[.14em] uppercase text-[9px] mt-4 mb-1.5">Tools</div>
        {nextTools.length === 0 && <div className="text-white/35">every tier earned</div>}
        {nextTools.map((d) => {
          // Counted through `have` rather than `canCraftTool`, which wants a whole Inventory (and a
          // BankState) — the panel only ever needs counts, and faking an Inventory to ask a
          // yes/no question is how a display drifts from the thing that actually spends.
          // `onCraftTool` still calls the real `canCraftTool` before spending; this only greys a row.
          const can = d.recipe.every(i => have(i.itemId) >= i.count)
          return (
            <button key={d.id} disabled={!can} onClick={() => onCraftTool(d.id)}
                    className={`w-full text-left mb-1 px-2 py-1.5 rounded border transition-colors ${
                      can ? 'border-white/15 hover:border-amber-200/50 hover:bg-white/5 text-white/90'
                          : 'border-white/5 text-white/30 cursor-not-allowed'}`}>
              <div className="flex justify-between gap-3">
                <span>{d.name}</span>
                <span className="text-white/45">tier {d.tier} {d.skillId}</span>
              </div>
              <div className="mt-0.5 text-[10px]"><Cost items={d.recipe} /></div>
            </button>
          )
        })}
      </div>
    </div>
  )
}

function SettingsPanel({ s, update, onClose }: {
  s: VoxelSettings
  update: (p: Partial<VoxelSettings>) => void
  onClose: () => void
}) {
  const Slider = ({ label, k }: { label: string; k: 'toon' | 'outline' | 'faceShading' | 'shadowLift' }) => (
    <label className="flex items-center gap-2 text-[11px] font-mono text-white/70">
      <span className="w-24 shrink-0">{label}</span>
      <input
        type="range" min={0} max={1} step={0.05} value={s[k]}
        onChange={e => update({ [k]: Number(e.target.value) } as Partial<VoxelSettings>)}
        className="flex-1 accent-amber-300"
      />
      <span className="w-8 text-right tabular-nums text-white/50">{s[k].toFixed(2)}</span>
    </label>
  )

  return (
    <div className="absolute top-3 right-3 w-72 bg-black/80 border border-white/15 rounded p-3 space-y-2.5">
      <div className="flex items-center justify-between">
        <span className="text-[11px] font-mono font-semibold tracking-wider text-white/90 uppercase">Render</span>
        <button onClick={onClose} className="text-white/40 hover:text-white/80 text-xs font-mono">esc / O</button>
      </div>

      <div className="flex gap-1.5">
        {(['natural', 'cartoon'] as RenderStyle[]).map(v => (
          <button
            key={v}
            onClick={() => update(withStyle(s, v))}
            className={`flex-1 py-1.5 rounded text-[11px] font-mono uppercase tracking-wider border
              ${s.style === v ? 'border-amber-300 text-amber-200 bg-amber-300/10' : 'border-white/15 text-white/50'}`}
          >{v}</button>
        ))}
      </div>

      {/* Each lever is exposed so the look can be judged by moving ONE at a time on the real world.
          A preset is a starting point; the call is Alex's. */}
      <Slider label="banding" k="toon" />
      <Slider label="outline" k="outline" />
      <Slider label="face light" k="faceShading" />
      <Slider label="shadow lift" k="shadowLift" />

      <p className="text-[10px] leading-relaxed text-white/35 font-mono pt-1">
        Both shading paths live in one shader program and are picked by a uniform, so switching
        costs nothing. Settings persist.
      </p>
    </div>
  )
}
