import { NextRequest, NextResponse } from 'next/server'
import { readFile, readdir, mkdir, unlink } from 'fs/promises'
import { join } from 'path'
import { safeWriteFile as writeFile } from '../lib/backup'
import { validateGraph } from '../dev/dialogue/validate'

const DIALOGUES_DIR = join(process.cwd(), 'src/app/shimmer/data/dialogues')
const INDEX_PATH = join(DIALOGUES_DIR, 'index.ts')
const SAFE_ID = /^[a-zA-Z0-9_-]+$/

// GET: list all dialogue graphs, or fetch one by ?id=
export async function GET(req: NextRequest) {
  try {
    const id = req.nextUrl.searchParams.get('id')

    if (id) {
      if (!SAFE_ID.test(id)) return NextResponse.json({ error: 'Invalid id' }, { status: 400 })
      // Return single graph
      const filePath = join(DIALOGUES_DIR, `${id}.json`)
      const content = await readFile(filePath, 'utf-8')
      return NextResponse.json(JSON.parse(content))
    }

    // List all graphs (summary: id, npcId, node count, tags)
    await mkdir(DIALOGUES_DIR, { recursive: true })
    const files = await readdir(DIALOGUES_DIR)
    const jsonFiles = files.filter(f => f.endsWith('.json'))

    const summaries = await Promise.all(jsonFiles.map(async f => {
      const content = await readFile(join(DIALOGUES_DIR, f), 'utf-8')
      const graph = JSON.parse(content)
      return {
        id: graph.id,
        npcId: graph.npcId,
        nodeCount: graph.nodes?.length ?? 0,
        edgeCount: graph.edges?.length ?? 0,
        tags: graph.metadata?.tags ?? [],
      }
    }))

    return NextResponse.json({ dialogues: summaries })
  } catch (e: unknown) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Unknown error' }, { status: 500 })
  }
}

// PUT: save/update a dialogue graph
export async function PUT(req: NextRequest) {
  try {
    const graph = await req.json()
    if (!graph.id || !SAFE_ID.test(graph.id)) return NextResponse.json({ error: 'Invalid graph id' }, { status: 400 })
    if (!graph.npcId) return NextResponse.json({ error: 'Missing npcId' }, { status: 400 })
    if (!graph.nodes || !Array.isArray(graph.nodes)) return NextResponse.json({ error: 'Missing nodes array' }, { status: 400 })
    if (!graph.entryNodeId) return NextResponse.json({ error: 'Missing entryNodeId' }, { status: 400 })

    // Ensure edges array exists
    if (!graph.edges) graph.edges = []

    // Add metadata
    graph.metadata = { ...graph.metadata, lastEdited: new Date().toISOString() }

    await mkdir(DIALOGUES_DIR, { recursive: true })
    const filePath = join(DIALOGUES_DIR, `${graph.id}.json`)
    await writeFile(filePath, JSON.stringify(graph, null, 2) + '\n', 'utf-8')

    // Regenerate index.ts
    await regenerateIndex()

    // Return validation feedback (save always succeeds — don't block WIP)
    const validation = validateGraph(graph)
    return NextResponse.json({ success: true, id: graph.id, validation })
  } catch (e: unknown) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Unknown error' }, { status: 500 })
  }
}

// DELETE: remove a dialogue graph
export async function DELETE(req: NextRequest) {
  try {
    const { id } = await req.json()
    if (!id || !SAFE_ID.test(id)) return NextResponse.json({ error: 'Invalid id' }, { status: 400 })

    const filePath = join(DIALOGUES_DIR, `${id}.json`)
    await unlink(filePath)
    await regenerateIndex()

    return NextResponse.json({ success: true, deleted: id })
  } catch (e: unknown) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Unknown error' }, { status: 500 })
  }
}

/** Regenerate data/dialogues/index.ts from the JSON files on disk. */
async function regenerateIndex() {
  const files = await readdir(DIALOGUES_DIR)
  const jsonFiles = files.filter(f => f.endsWith('.json')).sort()

  const imports: string[] = []
  const names: string[] = []

  for (const f of jsonFiles) {
    const baseName = f.replace('.json', '')
    const varName = baseName.replace(/[^a-zA-Z0-9]/g, '_').replace(/^(\d)/, '_$1')
    // camelCase the var name
    const camel = varName.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
    imports.push(`import ${camel} from './${baseName}.json'`)
    names.push(camel)
  }

  const content = `// Auto-generated — do not edit manually
// Regenerated by save-dialogue API route
import type { DialogueGraph } from '../../engine/dialogue-schema'
import { registerGraphs } from '../../engine/dialogue-runtime'

${imports.join('\n')}

const ALL_GRAPHS: DialogueGraph[] = [
  ${names.join(',\n  ')},
] as DialogueGraph[]

export function loadAllDialogues() {
  registerGraphs(ALL_GRAPHS)
}

export { ALL_GRAPHS }
`

  await writeFile(INDEX_PATH, content, 'utf-8')
}
