// Furniture placements per zone — design-time positions set via Map Editor
// Runtime furniture (player-placed) stored in save data, not here
// Generated by save-map API — do not edit manually

export interface FurniturePlacement {
  furnitureId: string
  tileX: number
  tileY: number
}

const GARDEN_FURNITURE: FurniturePlacement[] = []

const MYCELIAL_PATH_FURNITURE: FurniturePlacement[] = []

const MOONWELL_GLADE_FURNITURE: FurniturePlacement[] = []

const SPORE_HOLLOW_FURNITURE: FurniturePlacement[] = []

const TWILIGHT_THICKET_FURNITURE: FurniturePlacement[] = []

const THE_THRESHOLD_FURNITURE: FurniturePlacement[] = []

const MANA_SPRINGS_FURNITURE: FurniturePlacement[] = []

const SPIRIT_MEADOW_FURNITURE: FurniturePlacement[] = []

const MOONWELL_GLADE_GREGORY_S_HOME_FURNITURE: FurniturePlacement[] = []

export const FURNITURE_PLACEMENTS: Record<string, FurniturePlacement[]> = {
  garden: GARDEN_FURNITURE,
  'mycelial-path': MYCELIAL_PATH_FURNITURE,
  'moonwell-glade': MOONWELL_GLADE_FURNITURE,
  'spore-hollow': SPORE_HOLLOW_FURNITURE,
  'twilight-thicket': TWILIGHT_THICKET_FURNITURE,
  'the-threshold': THE_THRESHOLD_FURNITURE,
  'mana-springs': MANA_SPRINGS_FURNITURE,
  'spirit-meadow': SPIRIT_MEADOW_FURNITURE,
  'moonwell-glade-gregory-s-home': MOONWELL_GLADE_GREGORY_S_HOME_FURNITURE,
}
