// Zone Chests — one-time treasure containers placed via Map Editor
// When opened, they show a ChestPanel with pre-filled loot. Once empty, they disappear.
// Rendered as furniture sprites (chest/iron_chest/ornate_chest) in the world.
// Generated by save-map API — do not edit manually (except loot arrays)

import type { ItemStack } from '../engine/inventory'

export interface ZoneChestPlacement {
  id: string          // "zonechest_<zone>_<tileX>_<tileY>"
  tileX: number
  tileY: number
  zoneId: string
  chestType: string   // furniture ID: 'chest', 'iron_chest', 'moss_chest', etc.
  loot: { itemId: string; count: number }[]  // items pre-filled into the chest
  claimable?: boolean // if true, player can take the chest itself as decoration
}

/** Generate deterministic zone chest ID from placement */
export function zoneChestId(zoneId: string, tileX: number, tileY: number): string {
  return `zonechest_${zoneId}_${tileX}_${tileY}`
}

/** Convert loot array into SlotGrid for ChestStorage */
export function lootToSlots(loot: { itemId: string; count: number }[], slotCount: number): (ItemStack | null)[] {
  const slots: (ItemStack | null)[] = new Array(slotCount).fill(null)
  for (let i = 0; i < Math.min(loot.length, slotCount); i++) {
    slots[i] = { itemId: loot[i].itemId, count: loot[i].count }
  }
  return slots
}

// ---- Zone Chest Data ----
// Placements set via Map Editor, loot filled in manually or via editor
// Format mirrors static-pickups.ts and furniture-placements.ts patterns

const GARDEN_ZONE_CHESTS: ZoneChestPlacement[] = []
const MYCELIAL_PATH_ZONE_CHESTS: ZoneChestPlacement[] = []
const MOONWELL_GLADE_ZONE_CHESTS: ZoneChestPlacement[] = []
const SPORE_HOLLOW_ZONE_CHESTS: ZoneChestPlacement[] = []
const TWILIGHT_THICKET_ZONE_CHESTS: ZoneChestPlacement[] = []
const MANA_SPRINGS_ZONE_CHESTS: ZoneChestPlacement[] = []
const SPIRIT_MEADOW_ZONE_CHESTS: ZoneChestPlacement[] = []
const THE_THRESHOLD_ZONE_CHESTS: ZoneChestPlacement[] = []


const TEST_SANDBOX_ZONE_CHESTS: ZoneChestPlacement[] = []

export const ZONE_CHESTS: Record<string, ZoneChestPlacement[]> = {
  garden: GARDEN_ZONE_CHESTS,
  'mycelial-path': MYCELIAL_PATH_ZONE_CHESTS,
  'moonwell-glade': MOONWELL_GLADE_ZONE_CHESTS,
  'spore-hollow': SPORE_HOLLOW_ZONE_CHESTS,
  'twilight-thicket': TWILIGHT_THICKET_ZONE_CHESTS,
  'mana-springs': MANA_SPRINGS_ZONE_CHESTS,
  'spirit-meadow': SPIRIT_MEADOW_ZONE_CHESTS,
  'the-threshold': THE_THRESHOLD_ZONE_CHESTS,
  'moonwell-glade-gregory-s-home': [],
  'test-sandbox': TEST_SANDBOX_ZONE_CHESTS,
}
