// GENERATED by scripts/build-worker.mjs — do not edit.
// Content-hashed so a deployed worker can never be served from a stale cache entry.
export const VOXEL_WORKER_URL = '/voxel-gen.worker.c8119d6e30.js'
