// GENERATED by scripts/build-worker.mjs — do not edit.
// Content-hashed so a deployed worker can never be served from a stale cache entry.
export const VOXEL_WORKER_URL = '/voxel-gen.worker.3759224958.js'
export const TILE_WORKER_URL = '/tile-paint.worker.d78942642e.js'
