// Auto-generated — do not edit manually
// Regenerated by save-dialogue API route
import type { DialogueGraph } from '../../engine/dialogue-schema'
import { registerGraphs } from '../../engine/dialogue-runtime'

import communityGate from './community-gate.json'
import consoleInspect from './console-inspect.json'
import gregoryChallenge from './gregory-challenge.json'
import gregoryIntro from './gregory-intro.json'
import gregoryTending from './gregory-tending.json'
import gregorySendoff from './gregory-sendoff.json'
import studyObservation from './study-observation.json'
import thistlePrefight from './thistle-prefight.json'
import thistleReturn from './thistle-return.json'
import thistleDefeat from './thistle-defeat.json'
import sorrelPrefight from './sorrel-prefight.json'
import sorrelDefeat from './sorrel-defeat.json'
import brackPrefight from './brack-prefight.json'
import brackDefeat from './brack-defeat.json'
import atherWindsHook from './ather-winds-hook.json'
import thistleHome from './thistle-home.json'
import sorrelHome from './sorrel-home.json'
import brackHome from './brack-home.json'

const ALL_GRAPHS: DialogueGraph[] = [
  communityGate,
  consoleInspect,
  gregoryChallenge,
  gregoryIntro,
  gregoryTending,
  gregorySendoff,
  studyObservation,
  thistlePrefight,
  thistleReturn,
  thistleDefeat,
  sorrelPrefight,
  sorrelDefeat,
  brackPrefight,
  brackDefeat,
  atherWindsHook,
  thistleHome,
  sorrelHome,
  brackHome,
] as DialogueGraph[]

export function loadAllDialogues() {
  registerGraphs(ALL_GRAPHS)
}

export { ALL_GRAPHS }
